= UUID Criterion Validation

Each Criterion is defined in e-Certis and must use the *Universally Unique Identifier (UUID)* supplied by e-Certis:

[arabic]
. These UUIDs are 'constant', meaning that they are maintained by DG GROW and need to be used compulsory as they were issued by DG GROW.
. The value of each UUID are defined in the spreadsheets:
[loweralpha]
.. link:{url-tree}/codelists/ESPD-criterion.xlsx[ESPD-criterion]

The UUIDs defined in the ESPDRequest or ESPDResponse are fixed for the following elements:

[cols=",",options="header",]
|===
|*Spreadsheet row* | *XSD Path*
|{CRITERION | cac:TenderingCriterion/cbc:ID
|{QUESTION_GROUP or {REQUIREMENT_GROUP | cac:TenderingCriterion/cac:TenderingCriterionPropertyGroup/cbc:ID
|{QUESTION_SUBGROUP or {REQUIREMENT_SUBGROUP | cac:SubsidiaryTenderingCriterionPropertyGroup/cbc:ID 
|{LEGISLATION | cac:TenderingCriterion/cac:Legislation/cbc:ID
|===

Every QUESTION_GROUP or QUESTION_SUBGROUP that has the same structure (meaning QUESTION or QUESTION_SUBGROUP), share the same UUID, as they are the same.

== Tendering Criterion 

The validation of each criterion (cac:TenderingCriterion element) has the aim to check:

[arabic]
. cbc:ID, cbc:CriterionTypeCode, cbc:Name and cbc:Description are mandatory;
. cbc:ID values match with the ones supplied by e-Certis;
. cac:TenderingCriterionPropertyGroup structure matches with the QUESTION_GROUP or REQUIREMENT_GROUP (see Tendering Criterion Property Group and Subgroup section below).

== Tendering Criterion Property Group and Subgroup

The same validations are executed for the first level group of properties and sub-groups of properties. The rules applied are:

[arabic]
. The cbc:ID and cbc:PropertyGroupTypeCode are mandatory elements in the corresponding cbc:TenderingCriterion;
. cac:SubsidiaryTenderingCriterionPropertyGroup matches with QUESTION_SUBGROUP or REQUIREMENT_SUBGROUP (for each property group, the same validations are applied); 
. cac:TenderingCriterionProperty structure matches with QUESTION or REQUIREMENT or CAPTION (see Tendering Criterion Property section below). 

== Tendering Criterion Property 

The validation of Tendering Criterion Property (cac:TenderingCriterionProperty element) is checked as follows:

[arabic]
. cbc:TypeCode and cbc:ValueDataTypeCode are mandatory elements;
. cbc:ID and cbc:Description elements are mandatory, although their values are not validated;
. If cbc:TypeCode value is "CAPTION", cbc:ValueDataTypeCode value must be "NONE".  

== Note. Replacement of UUID by XML Path Like ID 

From ESPD v4.0.0, UUID is going to be replaced by XML Path Like ID in the data structure. 
For further details, see section "xref:3.10_XML_Path_Like_ID.adoc[3.10 XML Path Like ID]". 
