:doctitle: The ESPD Demo
:doccode: espd-main-prod-015
:author: NPJ
:authoremail: nicole-anne.paterson-jones@ext.ec.europa.eu
:docdate: January 2024

The https://docs.ted.europa.eu/espd-demo/[ESPD Demo Site] is a collection of tools in one place designed to help developers creating an ESPD Service.  The info video below explains more about what you can find on the site:

#Insert video#

== Distribution Files:

* The ESPD code list Excel and XML files
* The Model and Data Structure Excel files

These downloads are available for ESPD-EDM Versions 3.3.0 and 4.0.0 directly from the Demo site and downloads can be filtered by version.

== Code lists

* Information about the Code Lists used in the ESPD, name, versions, URI, agency, links to more information for each list.
* Contents of each code list i.e., the codes contained within each, translations of each code into all EU languages (if available), and an xml download of each code list.

This information is available for versions 3.3.0 and 4.0.0 of the ESPD-EDM and can be filtered by version and code list.

== UUID

The UUID tool lets you enter a criterion UUID directly or search for one via the list. Clicking on the "Check eCertis button" queries eCertis to verify if the UUID is stored by eCertis.

The list is ordered by ESPD version, then ItemID, ascending,  and can be scrolled through to find the desired version and UUID.

All criterion in all ESPD versions from v1.0.0 can be queried.

== View

The ESPD Model Viewer demonstrates how a criterion in the model might be represented in HTML in an ESPD Service. Individual criteria can be filtered for per version, which are then displayed on the page. 

The viewer is available for v3.3.0 and v4.0.0 of the ESPD-EDM.

== Examples

The Examples Generator allows developers to generate example Request and Response xml files according to their desired scenarios that can then be used for testing their ESPD Service development. These xml files are verified as being correct so they can be used without compounding errors in testing and creating confusion by being inaccurate themselves.

Currently v3.3.0 example xml files can be generated. 