:doctitle: The Distribution Package
:doccode: espd-v4.0.x-prod-005
:author: NPJ
:authoremail: nicole-anne.paterson-jones@ext.ec.europa.eu
:docdate: January 2024

The latest distribution package can be found on link:https://github.com/OP-TED/ESPD-EDM/tree/master[OP TED GitHub]

== The Code tab
=== Subfolders in the ESPD-EDM Repository

==== Branches
The master branch contains the code.
The wgm-reports branch is for the Open user Community reports which are minutes of the monthly meetings
Only a master branch is maintained with different version tags.

==== README.md
this is the description of the contents, and a brief overview of what can be found where in the repository. It is also used as the release notes.

==== Folders under the latest version
The \_ESPDTeam_ foldervisible in earlier versions has been removed

===== The codelists folder
The *codelists folder* contains the ESPD-criterion.xlsx file, the “Criterion Exel File”, an internal template that is used to define the ESPD Request structure and from which “test” ESPD-Request and ESPD-Response xml files can be generated internally. These xml output files are made available to the OUC in the xml-examples folder.

* The *xslx-codelists-to-genericode* subfolder #contains the excel-to-gc-multilang-v1.0.xsl* #that...#

* The *gc* sub-folder contains all the generic codes that the ESPD uses. General code lists are downloaded and used as is, or a subset of them is used.

Transform files are used to generate technical code lists if there are many changes to do at one time. If there is a small change, e.g., to one code, the ESPD-codelists.xlsx file is used as the source file. The procedure for generating new code lists after changes can be found via this link.

#*The *BACH-DataBase-Ratios.xlsx* file#

#The *ESPD-CodeLists.xlsx* file#



===== The Conceptual-model folder
The README.md describes the content of the folder

The .eap and .xmi file include two views and diagrams of the conceptual model:

** Business oriented view (BOV) aimed at facilitating the understanding of the model and the business context, with references to the technical model, and;
** Technically oriented view (TOV) providing an UBL based schema with references to the business-oriented view, aligned with the eProcurement ontology.
Folder ESPD_CM_html contains the HTML version of the UML conceptual model. If you do not want to download the folder to view the model you can view it on the documentation page under ESPD-EDM CONCEPTUAL MODEL HTML.

===== The UBL-2.3 folder
This folder contains a redistribution package from UBL 2.3. It includes:

*mod:* contains files that describe and represent the information
*xsd:* contains the xsd schemas for the ESPD Request and Response
*xsdrt:* contains the xsd schemas for ESPD Request and Response required for the runtime.

===== The Validation folder
The validation folder contains the schematron and xsl files for the validation of the ESPD Request and Response xml files as well a link to the “testbed”, an online facility for validating the two xml documents. The procedure for updating the schematron files can be found vis this link.


===== The xml-examples folder

Contains default ESPDRequest and ESPDResponse xml samples and the criterion xml schema.

The older \__xslt__ file is used internally by the ESPD Team to create the xml.

The /ODS Data Structures to ESPD XML folder contains the transform files to create ESPDRequest and ESPDResponse xml sample files.

* The ESPDRequest-Annotated.xslt: creates the ESPD Request from the criterion excel file.
* The From-REQUEST-to-RESPONSE.xslt: creates the ESPD Response from the ESPD Request xml file.
Untagged content in the master branch is in development. To access the latest and/ or stable branch, one must go to a tagged version.

Earlier versions can be accessed via their tag and could have a completely different folder structure to the one described above.

== The Issues Tab
This tab contains all the questions and issues submitted to the ESPD team by the open user community. As of v4.0.0-rc, the issues have been tagged making them more easily searchable.

The ESPD team also raises issues here to inform the OUC of any decision and to open discussion for topics that do not need to, or cannot wait for, a monthly meeting.

include::partial$feedback.adoc[]

