Suggestions:

* tool (demo) showing what fields should be available plus their behaviour, per version - as in current demo
* ecertis/ other info sources integration
* uuid and path-like identifier explanations
* questions from the public


== Version 3.3

// Questions from bilateral meetings; Also read through Interproc Meetings in GitHub Issues

*_How are the Exclusion Grounds and Selection Criteria built at national level in v3.3.0 in the Excel file? Are the national criteria fixed in the Excel file? Do the purely national Exclusion Grounds come from eCertis. Is it possible to hardcode them?_*

(Keywords: sub-criteria, national criteria)

Sub questions:

* How to encode the national criteria in selection criteria? (we discussed concretely on SUBCRITERION from CRITERION 7) 

* Is it possible to extract national criteria directly from eCertis to populate the ESPD Request? 

*Answer:*

There are two different situations in the excel file: 

. The sub-criterion structure is present in the structure of each criterion in the Excel file. The sub-criteria from eCertis apply purely to a national level for Exclusion Grounds. The specialisation is meant to replace the general description in the excel file.  The details are not available in the ESPD as they are defined in eCertis, therefore they should come from eCertis and not from the ESPD.  

. Other elements in the Exclusion Grounds purely at national level: countries can specify them #on their side#. (see C24 as an example) 
#does this mean at national level? Rewrite#

In eCertis one can retrieve information about a criterion (selection and exclusion) based on the UUID. Usage of a UUID has the same since v1.0.2. and it has always been possible for an ESPD service to take the corresponding information from eCertis using the UUID. What eCertis does not have is the actual information for specific requirements. Some counties have no Exclusion Grounds at purely national level. Currently the only possibility is to use the UUID to get information about Exclusion Grounds and Selection Criteria. 

For Belgium, the reference to the national legislation is provided in eCertis. The implementation must therefore fetch the information from eCertis and populate the placeholders for national criteria (SUBCRITERION section) from the ESPD-EDM. For other countries who do not have this information in eCertis, this section does not apply. 

The LEGISLATION section is hardcoded in eCertis and is retrieved on demand. The user has to click on a link to fetch the information from eCertis, if it is available. By default, the EU legislation is displayed in the ESPD service. In future eCertis implementations, it will be mandatory for the national legislation to be included in eCertis and for the ESPD service to be able to retrieve this information automatically. This information is country specific. 

*_Has Belgium defined national sub-criteria in eCertis?_* 

#(Keywords: )#

*Answer:*

#Belgium specific? i.e. Belgium has 44... 
There are 44 criteria mapped to EU criteria #and 27 evidence#. The Exclusion Grounds and the Selection Criteria are partially aligned with the ESPD. The excel file contains only the description. The child elements (SUBCRITERION, LEGISLATION etc.) do not come from eCertis currently. The EU Legislation is hard coded in eCertis. In the future it will be possible to link to national law and regulations in eCertis. This is encoded in eCertis but not yet available in the ESPD EDM.  

*_Is there a reference to the lot associated to the Selection Criteria? It is confusing as to how this will be linked to the Request. If there are several lots, how are they going to be identified in the Response?_*

#(Keywords: )#

*Answer:*

In version 3.3.0 the rule is that #all lots are applied to all Exclusion Grounds#. Different lots can be defined for multiple Selection Criteria.  

The Request uses the element cac:ProcurementProjectLotReference in the criterion description; the Response uses  cac:ProcurementProjectLot in the header for the whole Response and so there is no need to repeat the element. 

The ESPD Request has a specific UBL element mapping for *LOTS* and specific lot *REQUIREMENTS*. In the ESPD Response the reference (Lot ID) is taken from the corresponding ESPD Request section for each LOT. The cardinality is 0..1 in the ESPD for the UBL element cac:ProcurementProjectLot. This implies that a given Supplier has to provide a Response per Lot, the ID of the corresponding section is the link between Request and Response. 

Multiple responses for LOT imply that, from the implementation point of view, the complexity of creating one ESPD Response per LOT should be hidden from the supplier. The supplier will only fill in one single online form to produce multiple ESPD Responses. For the buyer this has to be transparent so that they can process and identify the responses. The objective, for future ESPD implementations, is to be fully aligned with eForms and to import the ESPD Request from the system automatically i.e., not having to create it manually. 

eForms has another model for LOTS and the ESPD EDM will align with eForms in the future. In eForms there is a Selection Criteria for each lot. In v3.3.0 of the ESPD there are no different requirements for different lots, an ESPD-Response for each Lot must be created.  

*_The complexity due to multiple LOTS and REQUIREMENTS should be hidden from the buyer when they create an ESPD Request. It would be great to see how other countries have implemented this._* 

#(Keywords: )#

*Answer:*

In the procurement procedure the buyer defining the lots and countries should be able to define them in their systems. Those systems should be able to generate all ESPD documents. In any system this should be available independently of the ESPD service. (The code for this functionality might be available from Greece). 

*_ The Request contains Selection Criteria, and the lots linked to them can be identified. How can the lots be identified in the Response?_* 

#(Keywords: )#

*Answer:*

On the Request for each criterion, the UBL element is added, and this can be repeated. In the Response the supplier must specify to which lot they are responding to so that the specific Criterion is linked. If the supplier applies the criterion to three lots in a tender, there will be three ESPD Responses and all will have to specify which lot they refer to in the header.  

*_lots can be removed from the tender, so the Request must be updated and if a Selection Criteria refers only to one lot that has been removed then that Selection Criteria must be removed from Request._* #clarify# 

A6: Yes, if a LOT is removed from an ESPD, for any reasons, a #Change# NOTICE will be issued and the ESPD Request should be updated. The corresponding section related to the removed LOT is also removed or, if that was the only LOT, the entire selection criteria will be removed.  

*_How should the sub-contractors and parties relied upon fill in the ESPD Response?  Part of the response could come from different ESPDs - How are these Responses merged?_*

#(Keywords: )#

*Answer:*

Each party must provide their own Response (via the main tenderer). There is no need to merge the Responses. 

Following the current code list ‘eo-role-type ‘, available for v3.3.0 there are the following roles: Sole tenderer, Group leader, Group member, Other entity (relied upon) and Subcontractor. 

According to the specific supplier role, each actor must provide a separate full ESPD response or actor-applicable parts of the ESPD Response. 

The matrix in the documentation should be the guideline for filling in the ESPD Response. 

As a general rule: 

Sole tenderer and Group leader (as main suppliers) provide an ESPD Response. 

Other entity (relied upon) provides Selection Criteria for the part they are relied upon for.  

A Group member only completes the parts that apply to them. 

Subcontractors should provide all information except for Selection Criteria.  

#Check if done:#

#The table in Section I.2 In the Business Handbook (see below) should be corrected by the OP ESPD team:# 

#the Sole tenderer may have or not have a Subcontractor and an entity not relied upon. He must provide the Selection Criteria (add missing cross in the first column)#

#in a consortium we talk about Group leader and Group member. Those two roles should be split in the table to avoid confusion. Add the cross for Selection Criteria for both ST and GL. Remove cross from Subcontractor for Selection Criteria. The buyer communicates only with the Group leader.# 


*_How does one deal with selection criteria that apply to different lots, but have different requirements or thresholds. This is supported in v4, but how  do services that implement v3 deal with this? _* 

#(Keywords: )#

*Answer:* 

ESPD services implementing v3 have their own features as their service is based on UBL 2.3. 


*_Do the espd services allow buyers to create multiple ESPD requests for the same procurement? Is that even allowed according to the ESPD standard?_*

#(Keywords: )#

*Answer:* 

No, the services are not allowed to create multiple ESPD Requests for one procurement. Having several Requests for one procedure is not possible according to the ESPD standard.


*_Although the the OP informed us that LOT and GLO are implemented as in eForms already in ESPD v3, and that we should follow the eForms documentation, we need further clarification._* 

The v3.3.0 ESPD model does not contain the Lot Management in an explicit way, but it is indeed possible to adapt the service based on UBL 2.3 documents, which are aligned with eForms. The Selection Criteria that apply to different lots cannot be found in the Excel criterion file. 

The XML examples from v4 can be followed to understand how it could work in v3:

The ESPD Request and Response examples contain multiple lots where Lot Management is clearly showcased. The general approach is that for one single ESPD Request with several lots there could be several ESPD Responses, the example in V4 is one of the possible responses. 

The corresponding documentation and sites can be consulted at: 

For Lot Management approach for Selection Criteria: Selection criteria :: TED Developer Documentation (europa.eu) 

For Lot Management: The ESPD Request Document :: TED Developer Documentation (europa.eu) 

UBL 2.3 documents Request and Response  

In eForms, Selection Criteria are specified per lot. Lot-Selection Criteria-requirement structure would look like this: 

LOT 1 --> Selection Criteria A --> Requirement X 

LOT 2 --> Selection Criteria A --> Requirement Y 

In ESPD v3, the lots are specified for each Selection Criteria: not allowed to repeat the same Selection Criteria within the same ESPD Request. 

It would look like this in ESPD v3: 

Selection Criteria A --> LOT 1--> Requirement X 

Selection Criteria A --> LOT 2--> Requirement Y 

 

*_What if you want to duplicate the requirements section?_* / 

*_How we can still allow a buyer to use different requirements per lot, using ESPD v3._*

#(Keywords: )#

*Answer:*  

- For specific requirements it is possible for a buyer to specify different requirements per lot only as of version 4. In v3 it is possible to duplicate the requirements section (requirements group) but not the Selection Criteria section. If there are several general yearly turn-over requirements, then for each you define the lots and the requirements.  

Despite the fact that the structure is not explicit in the Criterion Excel file in v3, it is possible to achieve different requirements for different lots by using the UBL 2.3 structure: in the Request, the ProcurementProjectLot contains all the lots specified inside it. Then in the TenderingCriterion , ProcurementProjectLotReference, only the Lots needed are specified. For the Response, in TenderingCriterionResponse the Response corresponding to each Lot is specified. 

A helpful example can be found in v4:  

To have different thresholds for Lot 1 and 3, for example, the Lots in the TenderingCriterionResponse in the Response. You have to to validate that the supplier is answering the right question about the right Lot. 

For example, in the EvidenceSupplied, the Request has 5 Lots but the Response will only mention the specific lots for which the Economic Operator has to provide evidence. The OP #will provide an XML example of Request and Response in the documentation of v3.# It i possible to have different requirements per Lot and the instances of the ESPD created by Belgium will have to be ESPD compliant (validated using the ESPD validator). 

Belgium will first work on a development assuming that the requirements are the same for all lots.  

The #Excel file# is a good starting point but it is not complete. It is better for Belgium to refer to the Business Rules in the GitHub/espd-validation-schematron/schematron/Schematronv3.3.0. There are no constraints concerning the Lot Management specific to the ESPD. 

*_How often does Belgium need to retrieve the info from eCertis, considering that National Legislation will not change that quickly_*

#(Keywords: )#

*Answer:*  

National Regulation is at eCertis level so the link to the UUIDs from eCertis has to be taken into consideration when implementing their service. The short answer is if the law changes it has to be quickly implemented. Belgium could have an automatic regular check from their system checking the updates in eCertis.  

*_There are placeholders in the ESPD (blue lines in the Excel file) and that information is filled in with the information that the buyer can get from eCertis. Is this correct?_* 

#(Keywords: )#

*Answer:*  

Yes, in the ESPD Excel Criterion file this information corresponds to the legislation, and sub-criterion, sections. 

The ESPD Servicemust be customised for each country. 

Also, the UUIDs used in eCertis can be checked in the Demo site 


*_Following your proposal, it would be possible to create a v3.3.0 ESPD request with different requirements per lot for the same selection criterion. If we understood well, this would be supported in the UBL 2.3 standard the ESPD EDM is based upon. However, we did not find any proof to corroborate this._* 

Looking at https://github.com/OP-TED/ESPD-EDM/blob/main/ubl-2.3/xsd/common/UBL-CommonAggregateComponents-2.3.xsd ... 

LotsGroupType, TenderingCriterionType and TenderingCriterionResponseType are the only three places in ESPD allowing to reference a lot 

Lotsgroup can only be used inside LotDistributionType, which can only be used inside TenderingTerms, which can only be used inside ProcurementProjectLotType itself 

TenderingCriterionType is where we have the lot reference now, which is too high-level 

And then there's the response: although not documented in the Excel file, the XML does allow for the supplier to give a different response per lot 

However, that still doesn’t explain how the buyer can specify different requirements for the same criterion per lot, in the ESPD request. 

Are we still missing something? 

#(Keywords: )#

*Answer:*  

The OP ESPD Team will provide Belgium with a basic xml example to show how it could work. The simple case is: Exclusion Grounds apply to all lots, for Selection Criteria you must have at least one lot.  Then in the xml example you must specify which lot applies to a specific Selection Criteria. The structure is not ESPD specific, but from UBL 2.3. What changes is the way in which the group of lots are managed. Is it also possible to use a flat list of lots and just repeat them. OP will provide a new example to show how to use different thresholds for the same criteria for different lots. 

*_General yearly turnover:  Shouldn't evidence group 1 be nested in the repeatable group for amount+period?_*

#(Keywords: )#

*Answer:*  

The model is flexible and can be customised to your needs. The validation business rules are not strict about the placement of this particular evidence. If having specific business rules suits Belgium better, then go ahead and implement them.


*_If each country customises the service not all Responses will come through in other services. For example, it will not be possible to reuse the structure of the Yearly general turnover threshold for Lot 1. If a country wants to import a Belgium ESPD are there any rules that should be followed?_* 

#(Keywords: )#

*Answer:*  

The interoperability might be achieved by using the same version of ESPD model or if each ESPD Service implementer publishes their specific customisations. Lot management at Selection Criteria level was properly implemented in v4.0.0 and this version should be used if interoperability is a priority. In the future, new Directives will be adopted and a common ESPD Service might be provided for the Member States.  
 
In v3.3.0 the validation rules are flexible enough to accommodate the specific national legislation and business rules for each implementer. This is a feature intended to help Member States implement an ESPD Service. Another country will be able to import the xml using XSL transformation, if the customisations are provided by the ESPD Service implementer. Member States are encouraged to upgrade to the last ESPD version for maximum interoperability.  


*_General + Specific average turnover:    dateStartedTrading... is supposedly mandatory, but shouldn't it be nested inside the repeatable amount+period group?_* 

#(Keywords: )#

*Answer:*

The start trading date is part of a subgroup that is always displayed (ON*). It is possible to repeat the entire group since there is no hard rule imposed on the ESPD validation on this specific group._*  

*_General average turnover:   "average+additionalInfo" is not repeatable (we would expect it to be repeated per required fiscal year)_* 

#(Keywords: )#

*Answer:*  

It is possible to repeat the entire group since there is no hard rule imposed on the ESPD validation on this specific group.  

*_General/specific yearly/average turnovers (all 4): "evidences" are listed twice under the same property group, how does that work?_* 

#(Keywords: )#

*Answer:*  

The 1st evidence refers to the electronic evidence (URL) and the 2nd is specific evidence from the start date in case the 1st evidence is not available for the entire period for each Selection Criteria . 

*_References: Repeatability is foreseen on 2 levels: outer = group of references / inner = reference instances within a group. What if the ESPD request sets a requirement for e.g. 5 references: does it suffice to provide 1 group of 5, as well as 5 groups of 1? How are references counted?_*

#(Keywords: )#

*Answer:*  

Each EVIDENCE-ID must be uniquely identified and the reference (EVIDENCE-ID) is used in the response field. Depending on how you would like to implement you either declare the references ad-hoc or may constitute an #opis# from the beginning.  :  

*_Suitability-I and Suitability-II: Registration number is optional when yourAnswer = true?_* 

#(Keywords: )#

*Answer:*  

That is correct. Even if the answer is True not all Economic Operators can provide a registration number. They should provide the document upon request. 

*_Abilities_5: The data type for "number" is quantity_year?_* 

#(Keywords: )#

*Answer:*  

This is equivalent to a positive (#unsinged#) integer number greater or equal to 1. This was introduced to avoid having negative integer numbers or zero for number of years.   :  

*_Financial ratios: Shouldn't the question_subgroup be nested inside the inner requirement_subgroup (ee4...) instead of the outer one (cc1..)?_*

#(Keywords: )#

*Answer:*  

This can be customised according to your needs. The ESPD business rules do not impose a strict inclusion for this specific subgroup. 

////
*_Finally, we were wondering why entries from the occupation codelist seem to be missing when viewing the list in your new demo environment._*

 There we see for example: 

0             Armed forces occupations 
1             Managers 
2             Professionals 
3             Technicians and associate professionals 

Whereas the codelist itself seems more granular: 

0 - Armed forces occupations 
01 – Commissioned armed forces officers 
011 - Commissioned armed forces officers 
0110 - Commissioned armed forces officers 
0110.1 - Air force officer 


#(Keywords: )#

*Answer:*  

Thank you for the feedback. We have done now  the modification You can see now online the new way of displaying the list – that is the natural order from XML file. Previously the Code column was sorted alphabetically, hence 0, 1, 2 … 01, …, 011, …  

////

*_What is the difference between a Subcontractor and an entity relied upon_* 

#(Keywords: )#

*Answer:*  

Subcontractors are different from entities relied upon. This is also presented in separated sections in ESPD form. The UBL elements associated with the corresponding section are also different. #this does not answer the question#

*_How do we get the information for Qualifying party? Does each party in a consortium has to submit the info? What is the difference between Party and QualifyingParty?_*


#(Keywords: )#

*Answer:*  

The information for Qualifying party corresponds to #Annex 2, Part II, Section B# and it has specific data associated with it: pre-qualification system, Economic Operator size, etc. A party contains contact details about the Economic Operator. #answer Q re diffs between party and qualifyingparty#

*_In which criteria we put the other criteria?_* 


#(Keywords: )#

*Answer:*  

Other Criteria are named criteria for uniformity purposes, only ESPD internally. They were called like this to be able to have them all together in the Excel Criterion Taxonomy. They should not be treated as Criteria and the information provided by Economic Operator should be mapped to specific UBL structures, not a TenderingCriterion. #rewrite#

//== Version 4.0

//== Version 5.0
