:doctitle: ESPD Exchange Data Model (ESPD-EDM)
:doccode: espd-v4.0.x-prod-001
:author: NPJ
:authoremail: nicole-anne.paterson-jones@ext.ec.europa.eu
:docdate: January 2024

The European Single Procurement Document (ESPD) is a mandatory electronic form, in two parts, used by buyers to assess the suitability of suppliers tendering in a public procurement procedure. 

The documentation provided here explains the ESPD Exchange Data Model (ESPD-EDM) and covers the resources provided by the Publications Office, to help member states and commercial entities create an ESPD service. The service is the electronic online form which enables both parties in a procurement procedure to manage eligibility of a supplier in a procurement process.

The following information is provided for both business users (an overview of the ESPD), and technical users (resources for technical implementation of an ESPD Service).

== Release Documentation
* xref:ROOT:release_notes.adoc[Release Notes] +
The release notes for this version.
* link:{attachmentsdir}/ESPD_CM_html/index.html[Conceptual Model] +
The conceptual model for this version

== Information for Business Users
* xref:business:index.adoc[Business Information] +
An overview of the ESPD for business users
* xref:business:implementation.adoc[An ESPD Implementation] +
This section explains elements of an ESPD Implementation
* xref:business:using.adoc[The ESPD Online Form] +
Using an online ESPD form from both buyer and supplier perspectives
//* xref:espd-bus::creating.adoc[Creating an ESPD Service]
//* xref:espd-bus::overview_upgrades.adoc[Overview for Upgrading your Version]

== Technical Implementation of an ESPD Service
* xref:technical:index.adoc[Technical Information] +
Information for technical implementation
//* xref:espd-tech::tech_imp_roadmap.adoc[Road Map for Implementers]
//* xref:espd-tech::tech_upgrades.adoc[Upgrading an ESPD Version]
//* xref:espd-tech::demo.adoc[Demo ESPD Service Online]

include::partial$feedback.adoc[]