:doctitle: Release Notes
:doccode: espd-v3.3.x-prod-003
:author: NPJ
:authoremail: nicole-anne.paterson-jones@ext.ec.europa.eu
:docdate: January 2024

:sectnums:


== v3.3.0 (July 2023) 

ESPD-EDM version 3.2.0 focused on correcting minor errors in the data structure and code lists, as suggested by the Member States and stakeholders via the GitHub repositories issues workspace.

ESPD-EDM version 3.3.0 continued in the same vein, in the correction of minor errors in the data structure and code lists.


=== ESPD-EDM Criterion file - Data Structure 

Several issues relating to the data structure of the ESPD-EDM Criterion (taxonomy) file were resolved.

 * **Fixed Jira issue - "Update criterion files with codes of EU Vocabularies for v3.3.0"**
     ** In criterion C27, the element code "autorisation" has been replaced with the code "authorisation".
     ** In criterion C23, the element code "misinterpr" has been replaced with the code "misrepresent". 
     ** In criterion C23, the Name contents have been updated as well. "Guilty of misinterpretation" has been replaced by "Guilty of misrepresentation". 
     ** The worksheet "EG-Misinterpretation" has been renamed "EG-Misrepresentation". 

  * **Fixed GitHub issue https://github.com/OP-TED/ESPD-EDM/issues/368[#368] - Typing errors in taxonomy**
      ** Typing errors such as double spaces, duplicated words, and spelling issues, were corrected.


=== ESPD-EDM XSLT files

Changes to the ESPD-EDM XSLT files:

* ** Attributes values in the xslt files for the xml samples updated**
        ** SchemeVersionID value updated from “3.2.0” to “3.3.0”.
        ** ListVersionID value updated from “3.2.0” to “3.3.0”.
        ** The ESPD version in all comments updated to ESPD-V3.x.x

* **Updates to the "ESPDRequest-Annotated.xslt" file (missing element/attribute or incorrect value)**

      ** **Fixed GitHub issue https://github.com/OP-TED/ESPD-EDM/issues/387[#387] - Improper listVersionID attribute value in cbc:DocumentTypeCode**: cac:Language/cbc:LocaleCode/@listVersionID for  the codelist "language"
      ** **Fixed GitHub issue https://github.com/OP-TED/ESPD-EDM/issues/387[#387] - Improper listVersionID attribute value in cbc:DocumentTypeCode**: cbc:ExpectedCode/@listVersionID for  the codelist "eo-role-type"
      ** cac:Language/cbc:LocaleCode/@listAgencyID for  the codelist "language" 
      ** cbc:ExpectedCode/@listAgencyID for  the codelist "occupation" 
					
* **Updated the "From-REQUEST-to-RESPONSE.xslt" file (missing element/attribute or incorrect value)**

      ** **Fixed GitHub issue https://github.com/OP-TED/ESPD-EDM/issues/387[#387] - Improper listVersionID attribute value in cbc:DocumentTypeCode**: cbc:ResponseCode/@listVersionID for  the codelist "eo-role-type"

      ** **Fixed GitHub issue https://github.com/OP-TED/ESPD-EDM/issues/387[#387] - Improper listVersionID attribute value in cbc:DocumentTypeCode**: cbc:ResponseCode/@listVersionID for  the codelist "country"

      ** **Fixed GitHub issue https://github.com/OP-TED/ESPD-EDM/issues/390[#390] - PERCENTAGE Questions: Artifact Examples and Shematrons Inconsistency**: cbc:ResponseQuantity/@unitCode replaced by cbc:ResponseNumeric/@format
      ** cbc:ResponseCode/@listAgencyID for  the codelist "occupation" 

 * **Updated the xslt file "EconomicOperatorData.xslt" (missing element/attribute or incorrect value)**
       ** **Fixed GitHub issue https://github.com/OP-TED/ESPD-EDM/issues/387[#387] - Improper listVersionID attribute value in cbc:DocumentTypeCode**: cac:Party/cbc:IndustryClassificationCode/@listVersionID for  the codelist "economic-operator-size"

* **Updated the "Legislation.xslt" file (missing element/attribute or incorrect value)**

      ** **Fixed GitHub issue https://github.com/OP-TED/ESPD-EDM/issues/387[#387] - Improper listVersionID attribute value in cbc:DocumentTypeCode**: cac:Language/cbc:LocaleCode/@listVersionID for  the codelist "language"
      ** cac:Language/cbc:LocaleCode/@listAgencyID for  the codelist "language" 
     
* **Converted samples from Excel to XML format with the updated XSLT**

The updated XSLT files were then used to generate the XML samples now available in the GitHub folder, https://github.com/OP-TED/ESPD-EDM/tree/master/xml-examples[xml-examples].


=== Code Lists

ESPD version was updated in the technical code list files to match the current version (specific files can be found in the folder https://github.com/OP-TED/ESPD-EDM/tree/v3.3.0/codelists/gc[codelists/gc]), for tags: Version, CanonicalURI, CanonicalVersionURI, LocationURI.

The label "ESPD-EDMv3.3.0" was added to the sheet, "ProfileExecutionID", (in the last row of the table) of the Excel file https://github.com/OP-TED/ESPD-EDM/blob/master/\_\_ESPDTeam\_\_/ESPD-CodeLists.xlsx[ESPD-CodeLists.xlsx] .

* **Fixed GitHub issue https://github.com/OP-TED/ESPD-EDM/issues/387[#387] - Improper listVersionID attribute value in cbc:DocumentTypeCode**

This GitHub issue led to a broader review of the code lists relating to the value of the attribute "listVersionID". This attribute value was found to be incorrect in several code lists (DocRefContentType, Language, EoRoleType, Country, EconomicOperatorSize), and in various artefacts (CodeLists, XSLT, XML, Schematron). Updates were made in both the XSLT and Schematron files:

     ** XSLT files:  RootElements-Annotated.xslt, From-REQUEST-to-RESPONSE.xslt, ESPDRequest-Annotated.xslt, Legislation.xslt, EconomicOperatorData.xslt, ContractingAuthorityData-RequestResponse.xslt
     ** Schematron files: "./common/sch/01-ESPD-common-cl-attributes.sch", "./common/sch/01-ESPD-codelist-values.sch", "./common/sch/04-ESPD-common-other-br" 
     
The corresponding generic code files, and the corresponding XML files, were then generated.


=== Validation - Interoperability Testbed

The Interoperability Testbed https://www.itb.ec.europa.eu/espd/upload[ESPD validator] was updated:

* **Fixed GitHub issue https://github.com/OP-TED/ESPD-EDM/issues/387[#387] - Improper listVersionID attribute value in cbc:DocumentTypeCode**
     ** Schematron files: "./common/sch/01-ESPD-common-cl-attributes.sch", "./common/sch/01-ESPD-codelist-values.sch", "./common/sch/04-ESPD-common-other-br"  

* **Fixed GitHub issue https://github.com/OP-TED/ESPD-EDM/issues/390[#390] - PERCENTAGE Questions: Artifact Examples and Shematrons Inconsistency**
     ** Schematron file: "./common/sch/03-ESPD-resp-criterion-br.sch"

* Generated the ESPD validator for the Request and the Response for v3.3.0, with the latest entry files (generic code files for codelists, xml files for the ESPD Request and the ESPD Response).


=== Online documentation - espd-docs GitHub Repository 

The updated online documentation is available at https://docs.ted.europa.eu/home/index.html[Ted Developer Docs].
         
**Attribute value updates**

* The attribute value for the ESPD version has been updated across the online documentation (the version value for attributes schemeVersionID, listVersionID).

* The attribute value for "listVersionID" has been updated across the online documentation for the relevant code lists following the fix of GitHub issue https://github.com/OP-TED/ESPD-EDM/issues/387[#387] .

* Datatype "Percentage" relating to UBL element "ResponseQuantity" has been updated across the online documentation, now relating to the UBL element "ResponseNumeric", following the fix of GitHub issue https://github.com/OP-TED/ESPD-EDM/issues/390[#390].

* The code value or text relating to "autorisation" was updated to "authorisation" across the online documentation.

* The code value or text relating to "misinterpr" or "misinterpretation" was updated to "misrepresent" or "misrepresentation" across the online documentation.


**Release Notes** 

Release Notes were updated in the online documentation.

**Readme file** 

The Readme file in the GitHub repository was updated for v3.3.0.

include::partial$feedback.adoc[]