:sectnums:
= Release Notes

== v3.3.0 (July 2023) 

The ESPD-EDM version 3.2.0 was focused mainly on correcting minor errors in the data structure and the codelists, as suggested by the Member States and stakeholders via the GitHub repositories issues workspace.
The ESPD-EDM version 3.3.0 focuses also on correcting other minor errors in the data structure and the codelists.   


=== ESPD-EDM Criterion file - Data Structure 

Several issues have been resolved related to the data structure of the ESPD-EDM Criterion (taxonomy) file. 

 * **Fix Jira issue - "Update criterion files with codes of EU Vocabularies for v3.3.0**
     ** In criterion C27, the element code "autorisation" has been replaced with the code "authorisation".
     ** In criterion C23, the element code "misinterpr" has been replaced with the code "misrepresent". 
     ** In criterion C23, the Name contents have been updated as well. "Guilty of misinterpretation" has been replaced by "Guilty of misrepresentation". 
     ** The worksheet "EG-Misinterpretation" has been renamed "EG-Misrepresentation". 

  * **Fix GitHub issue https://github.com/OP-TED/ESPD-EDM/issues/368[#368] - Typo's in taxonomy**
      ** Typo errors such as double spaces and duplicated words, as well as spelling issues, have been fixed.


=== ESPD-EDM XSLT files

The following changes have been performed related to the ESPD-EDM XSLT files:

* **Updating attributes values in the xslt files for the xml samples** 
        ** SchemeVersionID value is “3.3.0” and not “3.2.0”.
        ** ListVersionID value is “3.3.0” and not “3.2.0”. 
        ** The right ESPD version in comments is ESPD-V3.x.x 

* **Updating the xslt file "ESPDRequest-Annotated.xslt" (missing element/attribute or incorrect value)** 
      ** **Fix GitHub issue https://github.com/OP-TED/ESPD-EDM/issues/387[#387] - Improper listVersionID attribute value in cbc:DocumentTypeCode**: cac:Language/cbc:LocaleCode/@listVersionID for  the codelist "language" 
      ** **Fix GitHub issue https://github.com/OP-TED/ESPD-EDM/issues/387[#387] - Improper listVersionID attribute value in cbc:DocumentTypeCode**: cbc:ExpectedCode/@listVersionID for  the codelist "eo-role-type" 
      ** cac:Language/cbc:LocaleCode/@listAgencyID for  the codelist "language" 
      ** cbc:ExpectedCode/@listAgencyID for  the codelist "occupation" 
					
* **Updating the xslt file "From-REQUEST-to-RESPONSE.xslt" (missing element/attribute or incorrect value)** 
      ** **Fix GitHub issue https://github.com/OP-TED/ESPD-EDM/issues/387[#387] - Improper listVersionID attribute value in cbc:DocumentTypeCode**: cbc:ResponseCode/@listVersionID for  the codelist "eo-role-type" 
      ** **Fix GitHub issue https://github.com/OP-TED/ESPD-EDM/issues/387[#387] - Improper listVersionID attribute value in cbc:DocumentTypeCode**: cbc:ResponseCode/@listVersionID for  the codelist "country" 
      ** **Fix GitHub issue https://github.com/OP-TED/ESPD-EDM/issues/390[#390] - PERCENTAGE Questions: Artifact Examples and Shematrons Inconsistency**: cbc:ResponseQuantity/@unitCode replaced by cbc:ResponseNumeric/@format 
      ** cbc:ResponseCode/@listAgencyID for  the codelist "occupation" 

 * **Updating the xslt file "EconomicOperatorData.xslt" (missing element/attribute or incorrect value)** 
       ** **Fix GitHub issue https://github.com/OP-TED/ESPD-EDM/issues/387[#387] - Improper listVersionID attribute value in cbc:DocumentTypeCode**: cac:Party/cbc:IndustryClassificationCode/@listVersionID for  the codelist "economic-operator-size" 

* **Updating the xslt file "Legislation.xslt" (missing element/attribute or incorrect value)** 
      ** **Fix GitHub issue https://github.com/OP-TED/ESPD-EDM/issues/387[#387] - Improper listVersionID attribute value in cbc:DocumentTypeCode**: cac:Language/cbc:LocaleCode/@listVersionID for  the codelist "language" 
      ** cac:Language/cbc:LocaleCode/@listAgencyID for  the codelist "language" 
     
* **Converting samples from Excel to XML format with the Updated XSLT** 

The resulting updated XSLT files have been used to generate the XML samples available in the GitHub folder https://github.com/OP-TED/ESPD-EDM/tree/master/xml-examples[xml-examples].  


=== Code Lists

ESPD version has been updated in the technical codelist files to match the current version (specific files can be found in the folder https://github.com/OP-TED/ESPD-EDM/tree/v3.3.0/codelists/gc[codelists/gc]), for tags: Version, CanonicalURI, CanonicalVersionURI, LocationURI. 

The label "ESPD-EDMv3.3.0" has been added in the related sheet "ProfileExecutionID" (in the last row of the table) of the excel file https://github.com/OP-TED/ESPD-EDM/blob/master/\_\_ESPDTeam\_\_/ESPD-CodeLists.xlsx[ESPD-CodeLists.xlsx] . 

* **Fix GitHub issue https://github.com/OP-TED/ESPD-EDM/issues/387[#387] - Improper listVersionID attribute value in cbc:DocumentTypeCode** 
This github issue has led to a broader review of the codelists related to the value of the attribute "listVersionID". This attribute value was indeed incorrect for several codelists (DocRefContentType, Language, EoRoleType, Country, EconomicOperatorSize) in various artefacts (CodeLists, XSLT, XML, Schematron). The updates have been made at different levels: XSLT files and Schematron files. 
     ** XSLT files:  RootElements-Annotated.xslt, From-REQUEST-to-RESPONSE.xslt, ESPDRequest-Annotated.xslt, Legislation.xslt, EconomicOperatorData.xslt, ContractingAuthorityData-RequestResponse.xslt
     ** Schematron files: "./common/sch/01-ESPD-common-cl-attributes.sch", "./common/sch/01-ESPD-codelist-values.sch", "./common/sch/04-ESPD-common-other-br" 
     
The corresponding generic code files and the corresponding XML files have been generated. 


=== Validation - Interoperability Testbed

Update of Interoperability Testbed https://www.itb.ec.europa.eu/espd/upload[ESPD validator]

* **Fix GitHub issue https://github.com/OP-TED/ESPD-EDM/issues/387[#387] - Improper listVersionID attribute value in cbc:DocumentTypeCode** 
     ** Schematron files: "./common/sch/01-ESPD-common-cl-attributes.sch", "./common/sch/01-ESPD-codelist-values.sch", "./common/sch/04-ESPD-common-other-br"  

* **Fix GitHub issue https://github.com/OP-TED/ESPD-EDM/issues/390[#390] - PERCENTAGE Questions: Artifact Examples and Shematrons Inconsistency** 
     ** Schematron file: "./common/sch/03-ESPD-resp-criterion-br.sch"

* Generating the ESPD validator, for the Request and the Response, for v3.3.0 with the latest entry files (generic code files for codelists, xml files for the ESPD Request and the ESPD Response). 


=== Online documentation - espd-docs GitHub Repository 

Update of the online documentation available at https://docs.ted.europa.eu/home/index.html[Ted Developer Docs]. 
         
**Attribute value updates**

Attribute value for ESPD version has been updated all over the online documentation. 
* version value for attributes schemeVersionID, listVersionID. 

Attribute value for "listVersionID" has been updated all over the online documentation for the various codelists. 
* following the fix of GitHub issue https://github.com/OP-TED/ESPD-EDM/issues/387[#387] . 

Datatype "Percentage" related to UBL element "ResponseQuantity" has been updated to be related to UBL element "ResponseNumeric" all over the online documentation. 
* following the fix of GitHub issue https://github.com/OP-TED/ESPD-EDM/issues/390[#390] . 

Code value or text related to "autorisation" has been updated to "authorisation" all over the online documentation. 

Code value or text related to "misinterpr" or "misinterpretation" has been updated to "misrepresent" or "misrepresentation" all over the online documentation. 


**Release Notes** 

Release Notes have been updated for the online documentation. 

**Readme file** 

The Readme file for v3.3.0 has been updated as well. 

