= Release Notes
include::partial$attributes.adoc[]


== v3.0.1 (early 2022)

=== Online documentation
Documentation updated as follow:

==== Technical Handbook
. *Section 2.3 ESPD Request cardinalities.*
* Removed sentence _'Notice that ESPD-EDM does not change anything else from the UBL-2.3 Schema.'_ because it did not help understanding what is kept from *UBL-2.3* and what is changed.

* *Figure 12.* ESPD-EDM 'QualificationApplicationRequest', UML diagram.
** _cac:EconomicOperatorParty_. 
*** Removed because it is not used in the *ESPD Request*.
** _cac:ProcurementProject_. 
*** Replaced by _cac:ProcurementProject/cbc:Description_ in alignment with *eForms*.
** _cac:ProcurementProjectLot_. 
*** Replaced by _cac:TenderingCriterion/cac:ProcurementProjectLotReference_.
** _cbc:QualificationApplicationTypeCode_. 
*** Removed because it is not used in *ESPD-EDM v3.0.x*.
** _cbc:WeightScoringMethodNote_. 
*** Removed because it is not used in *ESPD-EDM v3.0.x*.
** _cbc:WightingTypeCode_. 
*** Removed because it is not used in *ESPD-EDM v3.0.x*.

. *Section 2.4 Root elements.*
* *Table 5.* Class QualificationApplicationRequest, components required by the ESPD-EDM V3.0.0.
** _cac:ProcurementProject_.
*** Replaced by _cac:ProcurementProject/cbc:Description_ in alignment with *eForms*.
*** _Type_ updated from _Associated class_ to _Text_ in alignment with *eForms*.
*** _Cardinality_ updaged from _0..1_ to _1_ according to _Figure 12. ESPD-EDM 'QualificationApplicationRequest', UML diagram_.
*** _Requirement_ updated from _'This information is not required for the ESPD 3.0.0 since the information related to the procedure will come from eForms.'_ to _'This element is required in the ESPD, however it should be identical to that provided in eForms. In general the corresponding eForm should feed the corresponding ESPD with the corresponding data.'_.
** _cac:ProcurementProjectLot_. 
*** Replaced by _cac:TenderingCriterion/cac:ProcurementProjectLotReference_.
** _cbc:ProcedureCode_. 
*** _Cardinality_ updated from _0..1_ to _1_ in accordance to _Figure 12. ESPD-EDM 'QualificationApplicationRequest', UML diagram_.

. *Section 2.6 EU and national publications.*
* *XSD Schema.* _cac:AdditionalReferenceDocument_ replaced by _cac:AdditionalDocumentReference_.
* *Table 6.* Reference to additional documents, expected elements.
** _cac:AdditionalDocumentReference_. 
*** _Path_ Replaced _/QualificationApplicationRequest/cac:AdditionalReferenceDocument_ by _/QualificationApplicationRequest/cac:AdditionalDocumentReference_.

. *Section 2.7 Contracting Body.* 
* *Table 8.* Contracting body, expected elements.
** _cac:ContractParty_: 
*** Replaced by _cac:ContractingParty_ according to _Figure 11: QualificationApplicationRequest-2.3 main elements._.

* *Table 9.* Contracting body party, expected elements.
** _cac:PartyIdentification/cbc:Identifier_. 
*** _Requirement_ updated from _'More than one identifier can be specified. When possible use the VAT identification of the contracting body (see the VIES platform for a EU cross-border national VAT number verification system). '_ to _'When possible use the VAT identification of the contracting body (see the link:https://ec.europa.eu/taxation_customs/vies/[VIES] platform for a EU cross-border national VAT number verification system). When not possible a different identifier may be used.'_ because previous text was ambiguous.

. *Section 3. Common aspects for criteria.*
* *Figure 33.* Criterion - UML diagram.
** Updated all cardinalities from _1..*..*_ to _1..*_ because previous notation was wrong.

. *Section 6.2 ESPD Response XSD Schema.*
* _cac:ContractingAuthorityParty_. 
*** Replaced by _cac:ContractingParty_ according to _Figure 191. QualificationApplicationResponse XSD Schema, global view_.

. *Section 6.3 ESPD Response cardinalities.*
* *Figure 193.* ESPD-EDM 'QualificationApplicationResponse', UML diagram.
** _cac:ProcurementProject_. 
*** Replaced by _cac:ProcurementProject/cbc:Description_ because this is the information that is provided from eForms.
** _cac:ProcurementProjectLot_. 
*** Removed because in its place _cac:TenderingCriterion/cac:ProcurementProjectLotReference_ is used.
** _cbc:ProfileExecutionID_. 
*** _Cardinality_ updated from _0..1_ to _1_.
** _cbc:QualificationApplicationTypeCode_. 
*** Removed because it is not used in *ESPD-EDM v3.0.x*.
** _cbc:WeightScoringMethodNote_. 
*** Removed because it is not used in *ESPD-EDM v3.0.x*.
** _cbc:WightingTypeCode_. 
*** Removed because it is not used in *ESPD-EDM v3.0.x*.

. *Section 6.4 Root elements.*
* *Table 26.* Class QualificationApplicationResponse, components required by the ESPD-EDM V3.0.0.
** _cac:ContractingParty_. 
*** _Desciption_ updated with text _'See section <<2.7_Contracting_Body>> for more specification details.'_. where this element is described.
** _cac:EconomicOperator_. 
*** Replaced by _cac:EconomicOperatorParty_ according to _Figure 193. ESPD-EDM 'QualificationApplicationResponse', UML diagram._.
*** _Cardinality_ updated from _0..1_ to _1_.
** _cac:ProcurementProject_. 
*** Replaced by _cac:ProcurementProject/cbc:Description_ in alignment with *eForms*.
*** _Type_ changed from _Associated class_ to _Text_ in alignment with *eForms*.
*** Cardinality updated from _0..1_ to _1_ in accordance to _Figure 193. ESPD-EDM 'QualificationApplicationResponse', UML diagram._. 
*** _Requirement_ updated from _'Use this component to identify and describe the procurement administrative procedure. If the procurement procedure is divided into lots use the ProcurementProjectLot component to provide details specific to the lot and reserve the ProcurementProject component to describe the global characteristics of the procedure.'_ to _'This element is required in the ESPD, however it should be identical to that provided in eForms. In general the corresponding eForm should feed the corresponding ESPD with the corresponding data.'_.
** _cac:ProcurementProjectLot_. 
*** Removed because in its place _cac:TenderingCriterion/cac:ProcurementProjectLotReference_ is used.
** _cbc:ProcedureCode_ 
*** _Cardinality_ updated from _0..1_ to _1_ in accordance to _Figure 193. ESPD-EDM 'QualificationApplicationResponse', UML diagram._. 
*** _Type_ updated from _Identifier_ to _Code_.
** _cbc:ProfileExecutionID_. 
*** Added _Component_ with _Cardinality_ _1_.
** _cbc:UUID_. 
*** Updated _Cardinality_ from _0..1_ to _1_.

. *Section 6.5 Reference to publications and to the ESPD Request.*
* *Table 27.* Reference to the ESPD Request, expected elements.
** _cbc:DocumentDescription_. 
*** Added _Component_ with _Cardinality_ _0..1_.

. *Section 6.6 Economic Operator.*
* _cac:EconomicOperator_. 
*** Name appearences changed to _cac:EconomicOperatorParty_ according to _Figure 193. ESPD-EDM 'QualificationApplicationResponse', UML diagram_.

* *Table 35.* (Qualifying) economic operator party, expected elements.
** _cac:PartyIdentification/cbc:Identifier_. 
*** _Requirement_ updated from _'More than one identifier can be specified. Compulsory use of the attribute schemeAgencyID and highly recommended the use of the attribute schemeAgencyID. The preferred identifier is the national VAT number. Additional identifiers may be used'_ to _'When possible use the VAT identification of the contracting body (see the link:https://ec.europa.eu/taxation_customs/vies/[VIES] platform for a EU cross-border national VAT number verification system). When not possible a different identifier may be used.'_ because previous text was ambiguous.

* *Table 36. Economic operator postal address, expected elements.*
** _cac:EconomicOperator_. 
*** _Path_ updated from _/QualificationApplicationResponse/​cac:EconomicOperator/​cac:Party/​cac:PostalAddress_ to _/QualificationApplicationResponse/​cac:EconomicOperatorParty/​cac:Party/​cac:PostalAddress_ according to _Figure 198. cac:QualifyingParty element, XSD_.

. *Section 6.8 Evidences.*
* *Table 44*. Elements expected in an Evidence.
** _cbc:CandidateStatement_. 
*** _Requirement_ updated from _'None. Not currently used in ESPD.'_ to _'None. No rule is applied.'_ because previous text was misleading.

* *Table 45.* Elements expected from the 'cac:Evidence/cac:DocumentReference' element.
** _cac:Attachment/cac:ExternalReference/cbc:URI_. 
*** _Requirement_ updated from _'None. Not currently used in ESPD.'_ to _'None. No rule is applied.'_ because previous text was misleading.
** _cac:IssuerParty/cbc:WebsiteURI_. 
*** _Requirement_ updated from _'None. Not currently used in ESPD.'_ to _'None. No rule is applied.'_ because previous text was misleading.