
include::partial$attributes.adoc[]

== Release Notes

=== v3.0.0 (January 2021)

The ESPD-EDM v3.0.0 focuses on the ESPD-EDM alignment with eForms. This version provides changes and fixes suggested by the Member States and stakeholders via the GitHub repositories issues workspace. 
The list below details the updates included in this release.

### Online documentation

* Online documentation has been split in business and technical documentation to give a clearer view of each ESPD-EDM domain.

* **_‘Business Handbook’_** provides business domain information for the ESPD-EDM to help non-technical audiences to better understand ESPD-EDM and its context. 

* **_‘Technical Handbook’_** provides information related to the implementation of the ESPD-EDM and its technical aspects. 

### TOOP Requirements in ESPD-EDM (UBL2.2) Schema

A mapping between TOOP and UBL2.3 Schema has been made and tested. For more information, please refer to specific section on the online documentation. You can also access issue link:https://github.com/ESPD/ESPD-EDM/issues/277[#277] for a detailed discussion of this topic.

### Code Lists

Code lists have been updated for a closer alignment between ESD-EDM and eForms. Some code lists have been removed because the related information is available in eForms and the information can be gathered from eForms’ notices and placed into the proper placeholder. 

Code lists removed:

* BidType
* ProcedureType
* ProjectType
* ServicesProjectSubType
* LegislationType
* EvaluationMethodType (version 3.0.0 of the ESPD does not include weights, in order to keep the model as simple as possible)
* CPVCodes 

Code lists from EU Vocabularies used in ESPD-EDM:

* country
* currency
* economic-operator-size
* language 

A new code list has been added for the requirement of being enrolled in a professional register (criterion #25 Suitability I ‘Abilities’ – “prof-regist”) based on link:https://ec.europa.eu/esco/portal/occupation[ESCO]: 

* Occupation

### ESPD Criteria Data Structures (former ESPD Criteria Taxonomy)

Criteria Taxonomy has been renamed to _criterion_. The BASIC model present in ESPD-EDM v2.1.1 has been removed and only one model based on ESPD-EDM v2.1.1 EXTENDED model is provided.

Criteria code list codes have been updated to make them business agnostic and allow reuse across sectors (see _criterion_ tab within link:https://github.com/OP-TED/ESPD-EDM/blob/37fcfc29bfd031293b0b65f1d51c68494039c3fc/docs/src/main/asciidoc/modules/ROOT/dist/cl/xlsx/ESPD-CodeLists-V3.0.0.xlsx[ESPD-CodeLists-V3.0.0.xlsx]). This is reflected in criteria codes in column ‘ElementType’ of file link:https://github.com/OP-TED/ESPD-EDM/blob/37fcfc29bfd031293b0b65f1d51c68494039c3fc/docs/src/main/asciidoc/modules/ROOT/dist/cl/xlsx/ESPD-criterion-V3.0.0.xlsx[ESPD-criterion-V3.0.0.xlsx].

The following criteria have been removed from the file link:https://github.com/OP-TED/ESPD-EDM/blob/37fcfc29bfd031293b0b65f1d51c68494039c3fc/docs/src/main/asciidoc/modules/ROOT/dist/cl/xlsx/ESPD-criterion-V3.0.0.xlsx[ESPD-criterion-V3.0.0.xlsx]: 

* CRITERION.OTHER.CA_DATA.LOTS_SUBMISSION
* Criteria DEFENCE-SELECTION-OTHER and UTILITIES-SELECTION-OTHER
* CRITERION.OTHER.EO_DATA.LOTS_TENDERED

A QUESTION_SUBGROUP element has been added to selection criteria to provide information about whether the tenderer meets the criteria on its own or relies upon other entities. 

### UUIDs

New _UUID_ identifiers have been assigned for new criteria, groups and sub-groups. For a comprehensive list of the new _UUID_ and their creation reason, please refer to https://github.com/OP-TED/ESPD-EDM/tree/37fcfc29bfd031293b0b65f1d51c68494039c3fc/docs/src/main/asciidoc/modules/ROOT/assets/new_UUIDs_for_eCertis.xlsx[new_UUIDs_for_eCertis.xlsx].  

### Business Rules

Business rules used to validate the ESPD requests and responses have been updated as follows: 

* ‘Context’ element has been removed because it contained references to EXTENDED or BASIC type and this specification has been removed in ESPD-EDM v3.0.0; 
* Weightings’ validations have been removed because the ESPD-EDM v3.0.0 does not include weights;
* Business rules related to criteria not present in this version have been removed;
* Business rules related to code list not present in this version have been removed; 
* A rule has been added for the new lot management approach **_(one Lot/Group of Lots per ESPD Response)_**. **ESPD Request** includes exclusion and selection criteria for all lots while economic operators need to produce one **ESPD Response** per each lot tendered to. 
