:doctitle: Supporting and Related Projects
:doccode: espd-main-prod-005
:author: NPJ
:authoremail: nicole-anne.paterson-jones@ext.ec.europa.eu
:docdate: January 2024

The ESPD is associated with two further projects:

* eProcurement Ontology
* eForms
* eCertis

and supported by the eProcurement Ontology

== The eProcurement Ontology

The eProcurement Ontology (ePO) defines all the classes (concepts or names of entities) used in the ESPD, the relationships between classes, and the class attributes and cardinalities. The ePO's https://docs.ted.europa.eu/docs-staging/epo-home/stories_eAccess.html[eAccess Module] covers the ESPD Request, and the https://docs.ted.europa.eu/docs-staging/epo-home/stories_eSubmission.html[eSubmission module] covers the ESPD Response.

As with other public procurement projects, the ePO controls the vocabulary used in the ESPD, facilitating a common usage of concepts and their meanings. This enables https://commission.europa.eu/news/interoperable-europe-act-enters-force-today-2024-04-11_en[interoperability] and more effective https://single-market-economy.ec.europa.eu/single-market/public-procurement/digital-procurement/public-procurement-data-space-ppds_en[data operations], the improvement of which is a strong priority in EU public procurement.

== eForms

eForms is the legislated EU open standard used for publishing public procurement data.

It is accessed via a URL, just like the ESPD, and is used by public buyers to publish notices on Tender Electronic Daily, the online portal for publishing such eProcurement Notices.

eProcurement Notices can be a:

* Prior Information Notice, issued within the planning phase, and (sometimes) in the first part of the competition phase of the tender
* Contract Notice, issued within the competition phase of the tender
* Contract Work Notice, awarded after closure of the competition phase of the tender

The eForm is focused on the procurement and its publication, while the ESPD is focused on providing the items of evidence for the Criteria Exclusion Grounds, and the Selection Criteria for the procurement, published in the notice. It therefore follows the publication of the notice.

Technically, the eForm shares some information and reference elements with the ESPD. These could be common framework elements such as standards semantics, rules, terms, and definitions, upon which both are based i.e., used to create the services in the development phase or the transfer of certain information, and submitted in the eForms and the ESPD Service, in the operational phase. Aligning both services facilitates current and future interoperability.

== eCertis

https://ec.europa.eu/tools/ecertis/#/homePage[eCertis] is an information website, created by the EU Commission, that provides information at country level on the kind of evidence needed to fulfil a specific requirement in a specific European country. It is, effectively, a collection of certified information: criteria, identifiers for economic operators, or aspects of a directive, that is available to all member states. Everyone active in the procurement process, therefore, has a single common source for this information which reduces ambiguity and mistakes.

Contracting authorities can look up, firstly, at country level, what requirements are mandatory and, secondly, they do not have to create these requirements from scratch on their tender notices, they can include them directly from eCertis. This makes the tender process less burdensome.

If a member state or contracting authority wishes to publish their criteria (which generally stay the same) according to a directive, they just can register them in eCertis, which makes them available to all the participants in the procurement process.



Registration of the ESPD criteria in eCertis: All the criteria used in the ESPD, including exclusion grounds, are registered in eCertis with a unique identifier or code and the process of registering these, and the associated identifier, is coordinated carefully with eCertis. All criteria are published on eCertis with reference information such as the corresponding legislation, descriptions, and translations so that it is available to all participants in EU eProcurement.

include::partial$feedback.adoc[]