:doctitle: The Distribution Package
:doccode: espd-v3.3.x-prod-005
:author: NPJ
:authoremail: nicole-anne.paterson-jones@ext.ec.europa.eu
:docdate: January 2024

The latest distribution package can be found on https://github.com/OP-TED/ESPD-EDM/tree/master[OP TED GitHub]

== The Code tab
=== Subfolders in the ESPD-EDM Repository

==== Branches
The master branch contains the code. Only a master branch is maintained with different version tags.

The wgm-reports branch is for the Open user Community reports which are minutes of the monthly meetings.



==== README.md
this is the description of the contents, and a brief overview of what can be found where in the repository. It is also used as the release notes.

==== Folders under the latest version
===== The _ESPDTeam_ folder (for internal use only)

* *README.md* that describes the folder contents
* *Bach-Database-Ratios.xlsx*: source code for the financial-ratio-type code list that is maintained by the OP, sourced from the Bank of France.
* *ESPD-Codelists.xlsx*: Code list source definition that is transformed using the /XLSX CodeLists to Genericode/Excel_to_GC_Multilang_v1.0.xsl into the .gc codelist files in ESPD-EDM/codelists/gc. (A list of all the ESPD code lists).
* */XLSX CodeLists to Genericode*. Style sheet to generate genericode code lists from the definition in the ESPD-CodeLists.xlsx. (Instructions on how to generate the gc files are in the readme) ESPD-EDM/__ESPDTeam__/xslx-codelists-to-genericode at master · OP-TED/ESPD-EDM (github.com)


===== The codelists folder
The *codelists folder* contains the ESPD-criterion.xlsx file, the “Criterion Exel File”, an internal template that is used to define the ESPD Request structure and from which “test” ESPD-Request and ESPD-Response xml files can be generated internally. These xml output files are made available to the OUC in the xml-examples folder.

The *gc sub-folder* contains all the generic codes that the ESPD uses. General codelists are downloaded and used as is, or a subset of them is used.

Transform files are used to generate technical code lists if there are many changes to do at one time. If there is a small change, e.g., to one code, the ESPD-codelists.xlsx file is used as the source file. The procedure for generating new code lists after changes can be found via this link.



===== The Conceptual-model folder
The README.md describes the content of the folder

The .eap and .xmi file include two views and diagrams of the conceptual model:

** Business oriented view (BOV) aimed at facilitating the understanding of the model and the business context, with references to the technical model, and;
** Technically oriented view (TOV) providing an UBL based schema with references to the business-oriented view, aligned with the eProcurement ontology.
Folder ESPD_CM_html contains the HTML version of the UML conceptual model. If you do not want to download the folder to view the model you can view it on the documentation page under ESPD-EDM CONCEPTUAL MODEL HTML.



===== The Java-library folder
The java-library folder was provided for versions up to v2.x. It has not been maintained (as of V3.0.0) as the OUC is not restricted to using java and can develop their service in the language of their choice.



===== The UBL-2.3 folder
Contains the ubl 2.3. schema, a direct download from the UBL site.



===== The Validation folder
The validation folder contains the schematron and xsl files for the validation of the ESPD Request and Response xml files as well a link to the “testbed”, an online facility for validating the two xml documents. The procedure for updating the schematron files can be found vis this link.



===== The xml-examples folder
This folder contains examples of the ESPD Request and Response xml files for use by the OUC.

(The ESPD-criterion.xml file is not used by external users, it is an xml format of the xlsx file provided in the code list folder. It is used internally in the process that produces the schematron files used by the online Testbed.)

* The __xslt__ folder
is used internally by the ESPD Team to create the xml
The /ODS Data Structures to ESPD XML folder contains the transform files to create ESPDRequest and ESPDResponse xml sample files.
* The ESPDRequest-Annotated.xslt: creates the ESPD Request from the criterion excel file.
The From-REQUEST-to-RESPONSE.xslt: creates the ESPD Response from the ESPD Request xml file.
Untagged content in the master branch is in development. To access the latest and/ or stable branch, one must go to a tagged version.

Earlier versions can be accessed via their tag and could have a completely different folder structure to the one described above.

== The Issues Tab
This tab contains all the questions and issues submitted to the ESPD team by the open user community.

* Document requests
* Clarifying details and documentation regarding e.g., the distribution package or issues they had in their implementation.
* Requests for features proposing changes in the model or the document.

The ESPD team also raises issues here to inform the OUC of any decision and to open discussion for topics that do not need to, or cannot wait for, a monthly meeting.

include::partial$feedback.adoc[]

