:sectnums:
=== Code List Catalogue

This section collects all code lists used in *ESPD-EDM v3.0.0* with its classification, description and meta-data.

[[access-right-table,access-right]]
==== access-right
An example of how to use this code list can be found in <<access-right-xml-example>>.

[cols="1,2a"]
|===
|*Name* |*_access-right_*
|*Code list type* |Business-agnostic
|*Maintainer* |EU Vocabularies
|*Description* |Contains controlled vocabulary listing the access rights or restrictions to resources. It is designed for but not limited to DCAT descriptions of datasets.
|*Metadata* |
[cols=","]
!===
!*ShortName* !AccessRight
!*LongName* !access-right
!*ListID* !http://publications.europa.eu/resource/authority/access-right
!*Version* !20210317-0
!*CanonicalUri* !http://publications.europa.eu/resource/dataset/access-right
!*CanonicalVersionUri* !http://publications.europa.eu/resource/dataset/access-right/20210317-0
!*LocationUri* !http://publications.europa.eu/resource/distribution/access-right/20210317-0/xml/gc/AccessRight.gc
!*AgencyLongName* !Publications Office of the European Union
!*AgencyIdentifier* !

!===

|===

[[boolean-gui-control-type-table,boolean-gui-control-type]]
==== boolean-gui-control-type 
An example of how to use this code list can be found in <<boolean-gui-control-xml-example>>.

[cols="1,2a"]
|===
|*Name* |*_boolean-gui-control-type _*
|*Code list type* |Technical
|*Maintainer* |ESPD Team
|*Description* |This code list is only used in criterion 'Other economic or financial requirements' (*_finan-requ_*).
Contains values to be use by software implementations to display graphic control elements: radio buttons and check boxes. Code allows to represent values: true, false and not selected.
|*Metadata* |
[cols=","]
!===
!*ShortName* !BooleanGUIControlType
!*LongName* !
!*ListID* !boolean-gui-control-type 
!*Version* !3.0.1
!*CanonicalUri* !https://github.com/ESPD/ESPD-EDM
!*CanonicalVersionUri* !https://github.com/ESPD/ESPD-EDM/tree/3.0.1
!*LocationUri* !https://raw.githubusercontent.com/ESPD/ESPD-EDM/3.0.1/docs/src/main/asciidoc/dist/cl/gc/BooleanGUIControlType.gc
!*AgencyLongName* !
!*AgencyIdentifier* !

!===

|===

[[country-table,country]]
==== country
An example of how to use this code list can be found in <<country-xml-example>>.

[cols="1,2a"]
|===
|*Name* |*_country_*
|*Code list type* |Business-agnostic
|*Maintainer* |EU Vocabularies
|*Description* |Contains controlled vocabulary that lists concepts associated with names of countries and territories with a three letter coding.
|*Metadata* |
[cols=","]
!===
!*ShortName* !Country
!*LongName* !country
!*ListID* !http://publications.europa.eu/resource/authority/country
!*Version* !20210929-0
!*CanonicalUri* !http://publications.europa.eu/resource/dataset/country
!*CanonicalVersionUri* !http://publications.europa.eu/resource/dataset/country/20210929-0
!*LocationUri* !http://publications.europa.eu/resource/distribution/country/20210929-0/xml/gc/Country.gc
!*AgencyLongName* !Publications Office of the European Union
!*AgencyIdentifier* !OP

!===

|===

[[criterion-table,criterion]]
==== criterion
An example of how to use this code list can be found in <<criterion-xml-example>>.

[cols="1,2a"]
|===
|*Name* |*_criterion_*
|*Code list type* |Procurement specific
|*Maintainer* |EU Vocabularies
|*Description* |Contains coded criteria used for public procurement procedures.
|*Metadata* |
[cols=","]
!===
!*ShortName* !Criterion
!*LongName* !criterion
!*ListID* !http://publications.europa.eu/resource/authority/criterion
!*Version* !20210616-0
!*CanonicalUri* !http://publications.europa.eu/resource/dataset/criterion
!*CanonicalVersionUri* !http://publications.europa.eu/resource/dataset/criterion/20210616-0
!*LocationUri* !http://publications.europa.eu/resource/distribution/criterion/20210616-0/xml/gc/Criterion.gc
!*AgencyLongName* !Publications Office of the European Union
!*AgencyIdentifier* !OP

!===

|===

[[criterion-element-type-table,criterion-element-type]]
==== criterion-element-type 
An example of how to use this code list can be found in <<criterion-element-type-xml-example>>.

[cols="1,2a"]
|===
|*Name* |*_criterion-element-type _*
|*Code list type* |Technical
|*Maintainer* |ESPD Team
|*Description* |Contains coding for each type of structural element to render the ESPDRequest and ESPDResponse.
|*Metadata* |
[cols=","]
!===
!*ShortName* !CriterionElementType
!*LongName* !
!*ListID* !criterion-element-type 
!*Version* !3.0.1
!*CanonicalUri* !https://github.com/ESPD/ESPD-EDM
!*CanonicalVersionUri* !https://github.com/ESPD/ESPD-EDM/tree/3.0.0
!*LocationUri* !https://github.com/ESPD/ESPD-EDM/tree/3.0.0/docs/src/main/asciidoc/dist/cl/gc/CriterionElementType.gc
!*AgencyLongName* !
!*AgencyIdentifier* !

!===

|===

[[currency-type-table,currency-type]]
==== currency
An example of how to use this code list can be found in <<currency-xml-example>>.

[cols="1,2a"]
|===
|*Name* |*_currency_*
|*Code list type* |Business-agnostic
|*Maintainer* |EU Vocabularies
|*Description* |Contains controlled vocabulary that lists concepts associated with currencies and currency subunits. The concepts included are correlated with the ISO 4217 international standard.
|*Metadata* |
[cols=","]
!===
!*ShortName* !Currency
!*LongName* !currency
!*ListID* !http://publications.europa.eu/resource/authority/currency
!*Version* !20210929-0
!*CanonicalUri* !http://publications.europa.eu/resource/dataset/currency
!*CanonicalVersionUri* !http://publications.europa.eu/resource/dataset/currency/20210929-0
!*LocationUri* !http://publications.europa.eu/resource/distribution/currency/20210929-0/xml/gc/Currency.gc
!*AgencyLongName* !Publications Office of the European Union
!*AgencyIdentifier* !OP

!===

|===

[[docrefcontent-type-table,docrefcontent-type]]
==== docrefcontent-type 
An example of how to use this code list can be found in <<docrefcontent-type-xml-example>>.

[cols="1,2a"]
|===
|*Name* |*_docrefcontent-type _*
|*Code list type* |Technical
|*Maintainer* |ESPD Team
|*Description* |Contains coded possible document types referenced from the actual document.
This code list is maintained as technical for the time being. In the future it may be removed or published on EU Vocabularies.
|*Metadata* |
[cols=","]
!===
!*ShortName* !DocRefContentType
!*LongName* !
!*ListID* !docrefcontent-type 
!*Version* !3.0.1
!*CanonicalUri* !https://github.com/ESPD/ESPD-EDM
!*CanonicalVersionUri* !https://github.com/ESPD/ESPD-EDM/tree/3.0.1
!*LocationUri* !https://raw.githubusercontent.com/ESPD/ESPD-EDM/3.0.1/docs/src/main/asciidoc/dist/cl/gc/DocRefContentType.gc
!*AgencyLongName* !
!*AgencyIdentifier* !

!===

|===

[[economic-operator-size-table,economic-operator-size]]
==== economic-operator-size
An example of how to use this code list can be found in <<economic-operator-size-xml-example>>.

[cols="1,2a"]
|===
|*Name* |*_economic-operator-size_*
|*Code list type* |Business-agnostic
|*Maintainer* |EU Vocabularies
|*Description* |Contains different categories in which the tenderers to whom a contract can be awarded are classified, according to their size (using as criteria the number of employees).
|*Metadata* |
[cols=","]
!===
!*ShortName* !EconomicOperatorSize
!*LongName* !economic-operator-size
!*ListID* !http://publications.europa.eu/resource/authority/economic-operator-size
!*Version* !20210317-0
!*CanonicalUri* !http://publications.europa.eu/resource/dataset/economic-operator-size
!*CanonicalVersionUri* !http://publications.europa.eu/resource/dataset/economic-operator-size/20210317-0
!*LocationUri* !http://publications.europa.eu/resource/distribution/economic-operator-size/20210317-0/xml/gc/EconomicOperatorSize.gc
!*AgencyLongName* !Publications Office of the European Union
!*AgencyIdentifier* !

!===

|===

[[eoid-type-table,eoid-type]]
==== eoid-type 
An example of how to use this code list can be found in <<eoid-type-xml-example>>.

[cols="1,2a"]
|===
|*Name* |*_eoid-type _*
|*Code list type* |Business-agnostic
|*Maintainer* |ESPD Team
|*Description* |Contains coded partys identification type used in *_cac:PartyIdentification_*.
This code list is maintained as technical for the time being. In the future it may be removed or published on EU Vocabularies.
|*Metadata* |
[cols=","]
!===
!*ShortName* !EOIDType
!*LongName* !
!*ListID* !eoid-type 
!*Version* !3.0.1
!*CanonicalUri* !https://github.com/ESPD/ESPD-EDM
!*CanonicalVersionUri* !https://github.com/ESPD/ESPD-EDM/tree/3.0.1
!*LocationUri* !https://raw.githubusercontent.com/ESPD/ESPD-EDM/3.0.1/docs/src/main/asciidoc/dist/cl/gc/EOIDType.gc
!*AgencyLongName* !
!*AgencyIdentifier* !

!===

|===

[[eo-role-type-table,eo-role-type]]
==== eo-role-type
An example of how to use this code list can be found in <<eo-role-type-xml-example>>.

[cols="1,2a"]
|===
|*Name* |*_eo-role-type_*
|*Code list type* |Procurement specific
|*Maintainer* |EU Vocabularies
|*Description* |Contains codes identifying the role of the economic operator in the procurement.
|*Metadata* |
[cols=","]
!===
!*ShortName* !EoRoleType
!*LongName* !eo-role-type
!*ListID* !http://publications.europa.eu/resource/authority/eo-role-type
!*Version* !20210616-0
!*CanonicalUri* !http://publications.europa.eu/resource/dataset/eo-role-type
!*CanonicalVersionUri* !http://publications.europa.eu/resource/dataset/eo-role-type/20210616-0
!*LocationUri* !http://publications.europa.eu/resource/distribution/eo-role-type/20210616-0/xml/gc/EoRoleType.gc
!*AgencyLongName* !Publications Office of the European Union
!*AgencyIdentifier* !OP

!===

|===

[[financial-ratio-type-table,financial-ratio-type]]
==== financial-ratio-type 
An example of how to use this code list can be found in <<financial-ratio-type-xml-example>>.

[cols="1,2a"]
|===
|*Name* |*_financial-ratio-type _*
|*Code list type* |Procurement specific
|*Maintainer* |ESPD Team
|*Description* |Contains codes of the possible financial ratios to declare in selection criteria *_finan-rat_*.
This code list is maintained by the ESPD Team and codes are collected from Banque de France.
|*Metadata* |
[cols=","]
!===
!*ShortName* !FinancialRatioType
!*LongName* !financial-ratio-type 
!*ListID* !FinancialRatioType
!*Version* !1.0
!*CanonicalUri* !https://www.bach.banque-france.fr/
!*CanonicalVersionUri* !https://www.bach.banque-france.fr/
!*LocationUri* !https://github.com/ESPD/ESPD-EDM/tree/3.0.0/docs/src/main/asciidoc/dist/cl/gc/FinancialRatioType.gc
!*AgencyLongName* !BACH Banque de France
!*AgencyIdentifier* !BACH

!===

|===

[[language-table,language]]
==== language
An example of how to use this code list can be found in <<language-xml-example>>.

[cols="1,2a"]
|===
|*Name* |*_language_*
|*Code list type* |Business-agnostic
|*Maintainer* |EU Vocabularies
|*Description* |Contains controlled vocabulary that lists concepts associated with languages.
The concepts included are correlated with the ISO 639 international standard.
|*Metadata* |
[cols=","]
!===
!*ShortName* !Language
!*LongName* !language
!*ListID* !http://publications.europa.eu/resource/authority/language
!*Version* !20210929-0
!*CanonicalUri* !http://publications.europa.eu/resource/dataset/language
!*CanonicalVersionUri* !http://publications.europa.eu/resource/dataset/language/20210929-0
!*LocationUri* !http://publications.europa.eu/resource/distribution/language/20210929-0/xml/gc/Language.gc
!*AgencyLongName* !Publications Office of the European Union
!*AgencyIdentifier* !OP

!===

|===

[[occupation-table,occupation]]
==== occupation
An example of how to use this code list can be found in <<occupation-xml-example>>.

[cols="1,2a"]
|===
|*Name* |*_occupation_*
|*Code list type* |Technical
|*Maintainer* |ESPD Team
|*Description* |Contains codes for professional enrolment areas in which the Economic Operator must be registered in.
This code list is maintained by the ESPD Team but content is collected from the <<esco>> (from now on *ESCO*) classification. This code list remains as technical but in the future it could be published in EU Vocabularies or provided directly from *ESCO*.
The data type expected for this code is URL following the *ESCO* taxonomy identification that uses a URI as the key value.
|*Metadata* |
[cols=","]
!===
!*ShortName* !occupation
!*LongName* !
!*ListID* !occupation
!*Version* !3.0.1
!*CanonicalUri* !https://github.com/ESPD/ESPD-EDM
!*CanonicalVersionUri* !https://github.com/ESPD/ESPD-EDM/tree/3.0.1
!*LocationUri* !https://raw.githubusercontent.com/ESPD/ESPD-EDM/3.0.1/docs/src/main/asciidoc/dist/cl/gc/occupation.gc
!*AgencyLongName* !
!*AgencyIdentifier* !

!===

|===

[[profile-execution-id-table,profile-execution-id]]
==== profile-execution-id 
[cols="1,2a"]
|===
|*Name* |*_profile-execution-id _*
|*Code list type* |Technical
|*Maintainer* |ESPD Team
|*Description* |Contains coded identification and version the ESPD-EDM used to create the to <<xml>> instance. The identification may include the exact version of the specification.
[cols=","]
!===
!*ShortName* !ProfileExecutionID
!*LongName* !
!*ListID* !profile-execution-id 
!*Version* !3.0.1
!*CanonicalUri* !https://github.com/ESPD/ESPD-EDM
!*CanonicalVersionUri* !https://github.com/ESPD/ESPD-EDM/tree/3.0.1
!*LocationUri* !https://raw.githubusercontent.com/ESPD/ESPD-EDM/3.0.1/docs/src/main/asciidoc/dist/cl/gc/ProfileExecutionID.gc
!*AgencyLongName* !
!*AgencyIdentifier* !

!===

|===

[[property-group-type-table,property-group-type]]
==== property-group-type 
[cols="1,2a"]
|===
|*Name* |*_property-group-type _*
|*Code list type* |Technical
|*Maintainer* |ESPD Team
|*Description* |Contains coded types to be used by software implementations to control which elements to be rendered in the displayed user interface. 
[cols=","]
!===
!*ShortName* !PropertyGroupType
!*LongName* !
!*ListID* !property-group-type 
!*Version* !3.0.1
!*CanonicalUri* !https://github.com/ESPD/ESPD-EDM
!*CanonicalVersionUri* !https://github.com/ESPD/ESPD-EDM/tree/3.0.1
!*LocationUri* !https://raw.githubusercontent.com/ESPD/ESPD-EDM/3.0.1/docs/src/main/asciidoc/dist/cl/gc/PropertyGroupType.gc
!*AgencyLongName* !
!*AgencyIdentifier* !

!===

|===

[[response-data-type-table,response-data-type]]
==== response-data-type 
[cols="1,2a"]
|===
|*Name* |*_response-data-type _*
|*Code list type* |Technical
|*Maintainer* |ESPD Team
|*Description* |Contains identifiers used to descrive data type expected in criteria elements.
[cols=","]
!===
!*ShortName* !ResponseDataType
!*LongName* !
!*ListID* !response-data-type 
!*Version* !3.0.1
!*CanonicalUri* !https://github.com/ESPD/ESPD-EDM
!*CanonicalVersionUri* !https://github.com/ESPD/ESPD-EDM/tree/3.0.1
!*LocationUri* !https://raw.githubusercontent.com/ESPD/ESPD-EDM/3.0.1/docs/src/main/asciidoc/dist/cl/gc/ResponseDataType.gc
!*AgencyLongName* !
!*AgencyIdentifier* !

!===

|===