:sectnums:
[[code-list-catalogue,Annex I. Code List Catalogue]]
= Annex I. Code List Catalogue
include::partial$attributes.adoc[]

This section collects all code lists used in *ESPD-EDM* with its classification, description and meta-data.

[[access-right-table,access-right]]
== access-right
An example of how to use this code list can be found in xref:Tech_AnnexII_XML_Examples.adoc#access-right-xml-example[access-right xml Example].

[cols="1,2a"]
|===
|*Name* |*_AccessRight_*
|*Code list type* |Business-agnostic
|*Maintainer* |EU Vocabularies
|*Description* |Contains controlled vocabulary listing the access rights or restrictions to resources. It is designed for but not limited to DCAT descriptions of datasets.
|*Metadata* |
[cols=","]
!===
!*ShortName* !AccessRight
!*LongName* !access-right
!*ListID* !http://publications.europa.eu/resource/authority/access-right
!*Version* !20220316-0
!*CanonicalUri* !http://publications.europa.eu/resource/dataset/access-right
!*CanonicalVersionUri* !http://publications.europa.eu/resource/dataset/access-right/20220316-0
!*LocationUri* !https://op.europa.eu/en/web/eu-vocabularies/dataset/-/resource?uri=http://publications.europa.eu/resource/dataset/access-right
!*AgencyLongName* !Publications Office of the European Union
!*AgencyIdentifier* !OP

!===

|===

[[boolean-gui-control-type-table,boolean-gui-control-type]]
== boolean-gui-control-type 
An example of how to use this code list can be found in xref:Tech_AnnexII_XML_Examples.adoc#boolean-gui-control-type-xml-example[boolean-gui-control-type xml Example].

[cols="1,2a"]
|===
|*Name* |*_BooleanGUIControlType_*
|*Code list type* |Technical
|*Maintainer* |ESPD Team
|*Description* |This code list is only used in criterion 'Other economic or financial requirements' (*_finan-requ_*).
Contains values to be use by software implementations to display graphic control elements: radio buttons and check boxes. Code allows to represent values: true, false and not selected.
|*Metadata* |
[cols=","]
!===
!*ShortName* !BooleanGUIControlType
!*ListID* !boolean-gui-control-type 
!*Version* !3.2.0
!*CanonicalUri* !https://github.com/ESPD/ESPD-EDM
!*CanonicalVersionUri* !https://github.com/ESPD/ESPD-EDM/tree/v3.2.0
!*LocationUri* !https://github.com/ESPD/ESPD-EDM/tree/v3.2.0/codelists/gc/BooleanGUIControlType.gc

!===

|===

[[country-table,country]]
== country
An example of how to use this code list can be found in xref:Tech_AnnexII_XML_Examples.adoc#country-xml-example[country xml Example].

[cols="1,2a"]
|===
|*Name* |*_Country_*
|*Code list type* |Business-agnostic
|*Maintainer* |EU Vocabularies
|*Description* |Contains controlled vocabulary that lists concepts associated with names of countries and territories with a three letter coding.
|*Metadata* |
[cols=","]
!===
!*ShortName* !Country
!*LongName* !country
!*ListID* !http://publications.europa.eu/resource/authority/country
!*Version* !20220928-0
!*CanonicalUri* !http://publications.europa.eu/resource/dataset/country
!*CanonicalVersionUri* !http://publications.europa.eu/resource/dataset/country/20220928-0
!*LocationUri* !http://publications.europa.eu/resource/distribution/country/20220928-0/xml/gc/Country.gc
!*AgencyLongName* !Publications Office of the European Union
!*AgencyIdentifier* !OP

!===

|===

[[criterion-table,criterion]]
== criterion
An example of how to use this code list can be found in xref:Tech_AnnexII_XML_Examples.adoc#criterion-xml-example[criterion xml Example].

[cols="1,2a"]
|===
|*Name* |*_Criterion_*
|*Code list type* |Procurement specific
|*Maintainer* |EU Vocabularies
|*Description* |Contains coded exclusion and selection  criteria used for public procurement procedures.
|*Metadata* |
[cols=","]
!===
!*ShortName* !Criterion
!*LongName* !criterion
!*ListID* !http://publications.europa.eu/resource/authority/criterion
!*Version* !20210616-0
!*CanonicalUri* !http://publications.europa.eu/resource/dataset/criterion
!*CanonicalVersionUri* !http://publications.europa.eu/resource/dataset/criterion/20210616-0
!*LocationUri* !http://publications.europa.eu/resource/distribution/criterion/20210616-0/xml/gc/Criterion.gc
!*AgencyLongName* !Publications Office of the European Union
!*AgencyIdentifier* !OP

!===

|===

[[criterion-element-type-table,criterion-element-type]]
== criterion-element-type 
An example of how to use this code list can be found in xref:Tech_AnnexII_XML_Examples.adoc#criterion-element-type-xml-example[criterion-element-type xml Example].

[cols="1,2a"]
|===
|*Name* |*_CriterionElementType_*
|*Code list type* |Technical
|*Maintainer* |ESPD Team
|*Description* |Contains coding for each type of structural element to render the ESPDRequest and ESPDResponse.
|*Metadata* |
[cols=","]
!===
!*ShortName* !CriterionElementType
!*ListID* !criterion-element-type 
!*Version* !3.2.0
!*CanonicalUri* !https://github.com/ESPD/ESPD-EDM
!*CanonicalVersionUri* !https://github.com/ESPD/ESPD-EDM/tree/v3.2.0
!*LocationUri* !https://github.com/ESPD/ESPD-EDM/tree/v3.2.0/codelists/gc/CriterionElementType.gc
!===

|===

[[currency-table,currency]]
== currency
An example of how to use this code list can be found in xref:Tech_AnnexII_XML_Examples.adoc#currency-xml-example[currency xml Example].

[cols="1,2a"]
|===
|*Name* |*_Currency_*
|*Code list type* |Business-agnostic
|*Maintainer* |EU Vocabularies
|*Description* |Contains controlled vocabulary that lists concepts associated with currencies and currency subunits. The concepts included are correlated with the ISO 4217 international standard.
|*Metadata* |
[cols=","]
!===
!*ShortName* !Currency
!*LongName* !currency
!*ListID* !http://publications.europa.eu/resource/authority/currency
!*Version* !20220928-0
!*CanonicalUri* !http://publications.europa.eu/resource/dataset/currency
!*CanonicalVersionUri* !http://publications.europa.eu/resource/dataset/currency/20220928-0
!*LocationUri* !http://publications.europa.eu/resource/distribution/currency/20220928-0/xml/gc/Currency.gc
!*AgencyLongName* !Publications Office of the European Union
!*AgencyIdentifier* !OP

!===

|===

[[docrefcontent-type-table,docrefcontent-type]]
== docrefcontent-type 
An example of how to use this code list can be found in xref:Tech_AnnexII_XML_Examples.adoc#docrefcontent-type-xml-example[docrefcontent-type xml Example].

[cols="1,2a"]
|===
|*Name* |*_DocRefContentType_*
|*Code list type* |Technical
|*Maintainer* |EU Vocabularies
|*Description* |Contains coded possible document types referenced from the actual document.
This code list is maintained as technical for the time being. In the future it may be removed or published on EU Vocabularies.
|*Metadata* |
[cols=","]
!===
!*ShortName* !DocRefContentType
!*ListID* !docrefcontent-type 
!*Version* !20220928-0
!*ListID* !http://publications.europa.eu/resource/authority/docrefcontent-type
!*CanonicalUri* !http://publications.europa.eu/resource/dataset/docrefcontent-type
!*CanonicalVersionUri* !http://publications.europa.eu/resource/dataset/docrefcontent-type/20220928-0
!*LocationUri* !http://publications.europa.eu/resource/distribution/docrefcontent-type/20220928-0/xml/gc/DocrefcontentType.gc

!===

|===

[[economic-operator-size-table,economic-operator-size]]
== economic-operator-size
An example of how to use this code list can be found in xref:Tech_AnnexII_XML_Examples.adoc#economic-operator-size-xml-example[economic-operator-size xml Example].

[cols="1,2a"]
|===
|*Name* |*_EconomicOperatorSize_*
|*Code list type* |Business-agnostic
|*Maintainer* |EU Vocabularies
|*Description* |Contains different categories in which the operators are classified, according to their size (using as criteria the number of employees).
|*Metadata* |
[cols=","]
!===
!*ShortName* !EconomicOperatorSize
!*LongName* !economic-operator-size
!*ListID* !http://publications.europa.eu/resource/authority/economic-operator-size
!*Version* !20220316-0
!*CanonicalUri* !http://publications.europa.eu/resource/dataset/economic-operator-size
!*CanonicalVersionUri* !http://publications.europa.eu/resource/dataset/economic-operator-size/20220316-0
!*LocationUri* !http://publications.europa.eu/resource/distribution/economic-operator-size/20220316-0/xml/gc/EconomicOperatorSize.gc
!*AgencyLongName* !Publications Office of the European Union
!*AgencyIdentifier* !OP

!===

|===

[[eoid-type-table,eoid-type]]
== eoid-type 
An example of how to use this code list can be found in xref:Tech_AnnexII_XML_Examples.adoc#eoid-type-xml-example[eoid-type xml Example].

[cols="1,2a"]
|===
|*Name* |*_eoid-type_*
|*Code list type* |Technical
|*Maintainer* |ESPD Team
|*Description* |Contains coded partys identification type used in *_cac:PartyIdentification_*.
This code list is maintained as technical for the time being. In the future it may be removed or published on EU Vocabularies.
|*Metadata* |
[cols=","]
!===
!*ShortName* !EOIDType
!*ListID* !eoid-type 
!*Version* !3.2.0
!*CanonicalUri* !https://github.com/ESPD/ESPD-EDM
!*CanonicalVersionUri* !https://github.com/ESPD/ESPD-EDM/tree/v3.2.0
!*LocationUri* !https://github.com/ESPD/ESPD-EDM/tree/v3.2.0/codelists/gc/EOIDType.gc
!===

|===

[[eo-role-type-table,eo-role-type]]
== eo-role-type
An example of how to use this code list can be found in xref:Tech_AnnexII_XML_Examples.adoc#eo-role-type-xml-example[eo-role-type xml Example].

[cols="1,2a"]
|===
|*Name* |*_EoRoleType_*
|*Code list type* |Procurement specific
|*Maintainer* |EU Vocabularies
|*Description* |Contains codes identifying the role of the economic operator in each procurement procedure.
|*Metadata* |
[cols=","]
!===
!*ShortName* !EoRoleType
!*LongName* !eo-role-type
!*ListID* !http://publications.europa.eu/resource/authority/eo-role-type
!*Version* !20211208-0
!*CanonicalUri* !http://publications.europa.eu/resource/dataset/eo-role-type
!*CanonicalVersionUri* !http://publications.europa.eu/resource/dataset/eo-role-type/20211208-0
!*LocationUri* !http://publications.europa.eu/resource/distribution/eo-role-type/20211208-0/xml/gc/EoRoleType.gc
!*AgencyLongName* !Publications Office of the European Union
!*AgencyIdentifier* !OP

!===

|===

[[financial-ratio-type-table,financial-ratio-type]]
== financial-ratio-type 
An example of how to use this code list can be found in xref:Tech_AnnexII_XML_Examples.adoc#financial-ratio-type-xml-example[financial-ratio-type xml Example].

[cols="1,2a"]
|===
|*Name* |*_financial-ratio-type_*
|*Code list type* |Procurement specific
|*Maintainer* |ESPD Team
|*Description* |Contains codes of the possible financial ratios to declare in selection criteria *_finan-rat_*.
This code list is maintained by the ESPD Team and codes are collected from Banque de France.
|*Metadata* |
[cols=","]
!===
!*ShortName* !FinancialRatioType
!*ListID* !FinancialRatioType
!*Version* !3.2.0
!*CanonicalUri* !https://github.com/ESPD/ESPD-EDM
!*CanonicalVersionUri* !https://github.com/ESPD/ESPD-EDM/tree/v3.2.0
!*LocationUri* !https://github.com/ESPD/ESPD-EDM/tree/v3.2.0/codelists/gc/FinancialRatioType.gc
!*AgencyLongName* !BACH Banque de France
!*AgencyIdentifier* !BACH

!===

|===

[[language-table,language]]
== language
An example of how to use this code list can be found in xref:Tech_AnnexII_XML_Examples.adoc#language-xml-example[language xml Example].

[cols="1,2a"]
|===
|*Name* |*_Language_*
|*Code list type* |Business-agnostic
|*Maintainer* |EU Vocabularies
|*Description* |Contains controlled vocabulary that lists concepts associated with languages.
The concepts included are correlated with the ISO 639 international standard.
|*Metadata* |
[cols=","]
!===
!*ShortName* !Language
!*LongName* !language
!*ListID* !http://publications.europa.eu/resource/authority/language
!*Version* !20220928-0
!*CanonicalUri* !http://publications.europa.eu/resource/dataset/language
!*CanonicalVersionUri* !http://publications.europa.eu/resource/dataset/language/20220928-0
!*LocationUri* !http://publications.europa.eu/resource/distribution/language/20220928-0/xml/gc/Language.gc
!*AgencyLongName* !Publications Office of the European Union
!*AgencyIdentifier* !OP

!===

|===

[[occupation-table,occupation]]
== occupation
An example of how to use this code list can be found in xref:Tech_AnnexII_XML_Examples.adoc#occupation-xml-example[occupation xml Example].

[cols="1,2a"]
|===
|*Name* |*_Occupation_*
|*Code list type* |Technical
|*Maintainer* |ESPD Team
|*Description* |Contains codes for professional enrolment areas in which the Economic Operator must be registered in.
This code list is maintained by the ESPD Team but content is collected from the <<esco>> (from now on *ESCO*) classification. This code list remains as technical but in the future it could be published in EU Vocabularies or provided directly from *ESCO*.
The data type expected for this code is URL following the *ESCO* taxonomy identification that uses a URI as the key value.
|*Metadata* |
[cols=","]
!===
!*ShortName* !Occupation
!*LongName* !occupation
!*ListID* !occupation
!*Version* !20220615-0
!*CanonicalUri* !http://publications.europa.eu/resource/dataset/occupation
!*CanonicalVersionUri* !http://publications.europa.eu/resource/dataset/occupation/20220615-0
!*LocationUri* !http://publications.europa.eu/resource/distribution/occupation/20220615-0/xml/gc/Occupation.gc
!*AgencyLongName* !Directorate-General for Employment, Social Affairs and Inclusion
!*AgencyIdentifier* !EMPL

|===

[[profile-execution-id-table,profile-execution-id]]
== profile-execution-id 
[cols="1,2a"]
|===
|*Name* |*_ProfileExecutionID_*
|*Code list type* |Technical
|*Maintainer* |ESPD Team
|*Description* |Contains coded identification and version the ESPD-EDM used to create the to <<xml>> instance. The identification may include the exact version of the specification.
[cols=","]
!===
!*ShortName* !ProfileExecutionID
!*ListID* !profile-execution-id 
!*Version* !3.2.0
!*CanonicalUri* !https://github.com/ESPD/ESPD-EDM
!*CanonicalVersionUri* !https://github.com/ESPD/ESPD-EDM/tree/v3.2.0
!*LocationUri* !https://github.com/ESPD/ESPD-EDM/tree/v3.2.0/codelists/gc/ProfileExecutionID.gc
!===

|===

[[property-group-type-table,property-group-type]]
== property-group-type 
[cols="1,2a"]
|===
|*Name* |*_PropertyGroupType_*
|*Code list type* |Technical
|*Maintainer* |ESPD Team
|*Description* |Contains coded types to be used by software implementations to control which elements to be rendered in the displayed user interface. 
[cols=","]
!===
!*ShortName* !PropertyGroupType
!*ListID* !property-group-type 
!*Version* !3.2.0
!*CanonicalUri* !https://github.com/ESPD/ESPD-EDM
!*CanonicalVersionUri* !https://github.com/ESPD/ESPD-EDM/tree/v3.2.0
!*LocationUri* !https://github.com/ESPD/ESPD-EDM/tree/v3.2.0/codelists/gc/PropertyGroupType.gc
!===

|===

[[response-data-type-table,response-data-type]]
== response-data-type 
[cols="1,2a"]
|===
|*Name* |*_ResponseDataType_*
|*Code list type* |Technical
|*Maintainer* |ESPD Team
|*Description* |Contains identifiers used to descrive data type expected in criteria elements.
[cols=","]
!===
!*ShortName* !ResponseDataType
!*ListID* !response-data-type 
!*Version* !3.2.0
!*CanonicalUri* !https://github.com/ESPD/ESPD-EDM
!*CanonicalVersionUri* !https://github.com/ESPD/ESPD-EDM/tree/v3.2.0
!*LocationUri* !https://github.com/ESPD/ESPD-EDM/tree/v3.2.0/codelists/gc/ResponseDataType.gc
!===

|===
