:doctitle: The Distribution Package
:doccode: espd-tech-prod-033
:author: NPJ
:authoremail: nicole-anne.paterson-jones@ext.ec.europa.eu
:docdate: January 2024

The latest distribution package can be found on https://github.com/OP-TED/ESPD-EDM/tree/main[OP TED GitHub].
A brief explanation about "<> Code" and "⊙ Issues" tabs.

== The Code tab

=== Repository Structure

==== Branches

The *main* branch contains the latest released version of the code. Only a main branch is maintained with different version tags.

The wgm-reports branch is for the Open User Community presentations and reports of the meetings.

==== README.md
The README.md at the root level describes the contents and provides a brief overview of what can be found where in the repository.

=== Folders

The repository has the following folder structure:

[cols="30%,70%",options="header"]
|===
|Folder |Content

|*codelists*
|Contains the definition of technical code lists managed by the ESPD Team as well as references to the EU Vocabularies code lists. The code list files are in Genericode (.gc) format. These files are used in conjunction with the UBL XML structure and the ESPD Model to generate and validate ESPD Request and ESPD Response XML files. A `codelists.json` file provides the code list definitions in JSON format.

|*criterion*
|Contains the criterion structure definition. The file `espd-edm.json` contains the data structure of ESPD-EDM Exclusion Grounds and Selection Criteria in JSON format.

|*schemas*
|Contains the OASIS UBL 2.4 Distribution package. It includes: +
- `common/`: contains files that describe and represent the common elements and structures. +
- `maindoc/`: contains the XSD schemas for the ESPD Request and Response.

|*validation*
|Contains the ESPD-EDM validation files (Schematron and XSL). These files are created following the procedure described in the https://github.com/OP-TED/espd-validation-schematron[ESPD Validation Schematron repository], and the resulting XSL files are stored in the corresponding sub-folders in this repository. The required business rules validation files (XSL) are uploaded to the https://www.itb.ec.europa.eu/espd/upload[ITB Testbed]. +
 +
Sub-folders: +
- `common/cva/`: CVA file for code lists (`01-ESPD-codelist-values.cva`) +
- `common/sch/`: Schematron files for common elements and structure validation (code list values, attributes, criterion, etc.) +
- `ESPDRequest/sch/`: Schematron files for ESPD Request Business Rules +
- `ESPDRequest/xsl/`: Transformed Schematron-to-XSL files for ESPD Request +
- `ESPDResponse/sch/`: Schematron files for ESPD Response Business Rules +
- `ESPDResponse/xsl/`: Transformed Schematron-to-XSL files for ESPD Response

|===

NOTE: The `conceptual-model` folder and `ubl-2.3` folder from previous versions have been removed. The UBL 2.4 schema is now in the `schemas` folder. The Conceptual Model is accessible via the documentation site.

== Release Notes

Release notes for each release are available on https://github.com/OP-TED/ESPD-EDM/releases[GitHub Releases]. The distribution package for each release is attached to the corresponding release and the source code is tagged in the GitHub repository.

== The Issues Tab

This tab contains all the questions and issues submitted to the ESPD Team by the Open User Community.

* Document requests
* Clarifying details and documentation regarding e.g., the distribution package or issues they had in their implementation.
* Requests for features proposing changes in the model or the document.

The ESPD Team also raises issues here to inform the OUC of any decision and to open discussion for topics that do not need to, or cannot wait for, a monthly meeting.

include::partial$feedback.adoc[]
