:doctitle: Implementation Requirements
:doccode: espd-tech-prod-100
:author: SDC
:authoremail: Dragos-Constantin.STOICA@ext.ec.europa.eu
:docdate: May 2025

== Recommendations for ESPD Service implementation

The ESPD Team is proposing a possible way to approach ESPD Service implementation. We are fully aware that each Memeber State and User will have specific needs and systems to integrate in their ESPD Service implementation, therefore please refer to this documenta as a geneal guideline. The main objective of this document is to help ESPD Service implementer to evaluate the effort, make a realistic estimate for the implementation time and necessary resources, and understand the skills and competencies necessary for a successfult implementation.

There are a couple of situations that we encountered, concerning ESPD Service implementation:

- fresh start, a Memeber State that never had its own ESPD Service and used the one provided by another Member State
- using the intial version of the https://github.com/ESPD/ESPD-Service[ESPD Service]
- updating the existing ESPD Service

Each situation has a different starting point and it is important to understand the overall requirements for a full ESPD Service implementation.

In this document we will start from the hypothesis that it is a fresh implementation.

== Know-how requirements

ESPD Service is a facility that might be offered by a Memeber State as public open service or by private companies. The ESPD Service is part of the public eProcurement process. The legal framework is defined by link:\\espd-home\laws.html[EU Legislation] and National Legislation that is explicitly stored in https://ec.europa.eu/tools/ecertis/#/homePage[eCertis].

[quote,Commission Implementing Regulation (EU)2016/7]
____
The ESPD is a self-declaration by economic operators providing preliminary evidence replacing the certificates issued by public authorities or third parties. As provided in Article 59 of Directive 2014/24/EU, it is a formal statement by the economic operator that it is not in one of the situations in which economic operators shall or may be excluded; that it meets the relevant selection criteria and that, where applicable, it fulfils the objective rules and criteria that have been set out for the purpose of limiting the number of otherwise qualified candidates to be invited to participate. Its objective is to reduce the administrative burden arising from the requirement to produce a substantial number of certificates or other documents related to exclusion and selection criteria.
____

The right starting point is involving the Public Procurement experts and authorities in order to fully understand the problem, the desired result and all particular aspects related to the Member State requirements.

ESPD Service is intended for Economic Operators to fill in an ESPD. The data from ESPD should be eventually reused in other eProcurement steps and services. If this is the case then it is important to understand which version of ESPD is the most appropriate for your ESPD Service implementation.

== Technical requirements

The basic level of ESPD Service implementation has to probive a fexible and reliable way for the Economic Operator to fill in an ESPD form. If it is the case that the Buyer needs to fill in the ESPD Request then this functionality must be provided by the service, as well.

Most of ESPD Service implementations are Web Applications. They provide a step by step interface to fill in the ESPD form. The data model of the ESPD form is provided in the https://github.com/OP-TED/ESPD-EDM[ESPD-EDM].

The basic service needs, from technical point of view:  

- standard UI framework that will render forms
- standard framework that will allow to retain user data
- standard framework to render XML and PDF or any other standard form of data format for electronic data exchange
- integration with eCertis to retrieve specific information via API

Each eProcurement system has its specific technical requirements and it should be taken into consideration. This will add to the complexity of the ESPD Service implementation and must be taken into account by the ESPD Service implementer.


== Further steps

The ESPD Team provides public resources and information concerning the ESPD EDM, can answer specific ESPD EDM questions and put you in contact with the other Member States that successfully implemented ESPD Service.


include::partial$feedback.adoc[]