:doctitle: Validation and Conformance
:doccode: espd-tech-prod-036
:author: ESPD Team
:docdate: July 2026

// Split from: tech_validation.adoc (lines 141-250 — criteria-specific validation)
// Target section: Criteria

== ESPD Validation Steps

Depending on the type of application (ESPD Request or ESPD Response), different types of validations are executed:

image::https://kroki.io/pikchr/svg/eNq9mE1zqkgUhvf8ii4nCxmVggY03qpZ2KCrVN2MqZmaxd0gktg1BryA0fvvp7tpPrtJAmbIIqWc9pz3PP0elL6LwR9A1yAOld_AKUpwiqMQRM_Ai-PoAnAIdvgF7KJrkCh33oksNrQFVFbG7hu9CmJvD-zTFYzWT48u2AY_z0GSjtiH_OgYxUC_OraNDAM84-ORvFu7C9ek71Jwwfv0AAz797sYHAL8ckgBJK-VNLimsoReCkhdnvdywGmgKKhNSHKKwiTopIQk17JXXA29wF_-UC6YBLQLV6EFYALGumbZU12tK65WJotRU_IK-t-Aj2P_GID0gP1_a_85FMqkITuXEOYSEiZhOtM1U1X20SUESrZr9NPKymyS-efJBX97R7z36CaPwGj8F3qY_Xkml56xzy6uTqcjf8nRz6Bmaddkr46IADnIDVrb7oKBpBrrKGfEXVa5q7dqoK2buwKNsYSO5RAbfAVT9CFTdDPTzBw9oZocak-WQm3aswymdW506UT7ADzgJE3IfpKSZFPA9nwk_8e6AajvZz5ZciQrZm8srPlvnprNQGuHmw103FqH4z3JMGZ9TokyLVBVEsun0WyZRrq82DY7n8abNFMy1lkkY79DZpWmMd6dU1IBnRMcBkmzIHCi11dye3UeKou1xD90J0XU8QHrxMfQdAmf25VTXrbIazVvzovjxXscEoemv4oSEOT3elANoy0v0IbFXa9Xm7l8RLpiKW3TQyDNNpfMUbfuk9OQ7aMe7bcppOlk_S_EaWEuKm9adDadmHwtxvRnh2A-s26-cuH2E1OzhhvdXX7F1MDq1PwPHVB-C8n03Av--bAQ86hYpQOjniMEKx7qq5KmvJf4qBcHatahQKD-IOQyaU4ZieWnJup7eghisaZV8yJf9JlJcm3XWc-_YpLMDyapr3LKaymZIENvWuf9CtSYjfQdoPQcHbN0TGd17FFA30k6NzoMjV3mf4wj_xwPC8CquKKnSMbBkHGATQ5Pp8CnP5DfrVAuGhJD4YOeGhkFKLlvdJ8Dcl8aZBBQv0EQ5bEHOF3Wu3hE8P0driQzjQ_XdcX9XYSxfg1Zv30cT5IPZXnU2_JSkYyD1PPCw_pjHMx-Vh-PpSVqD9BDwrBLI9yklBGRPdcbVqszttExkNZggUEhiI74pDjWtyX5DoB6eTokOQsqDgJZK42ToSS_qRZHQ4Y2VxV0c04qtXLcRHIqCL-g6GqUe2TQTfqhAPrXPFibsHo8yKlm5yf0HCucUoVaopIfVeTxjixVy0TsxIuR1zWWxdtFbwFYQT8TRB8Ip7pm2sVndsEBh3t2_MqvsM7YiSbv-SX2fuUtwEYLXB7vr_RApbE8llumIjXzCI_zc1c41buLy07ynuPolVkxAWnEfsiGBNL4zjvRo9zKGhpKyhBbbbevtoXVqznZiFrVeV510Z5nIea5b-a5z_Ms2_MsxTzk-7GRiF5JspghxIwiBoUYzGPUZrUYqqOdtKOdiGgn7Wjrq5toUR3tpB1tPU8TLaqjnbSjrecR0KICLRLQogItEtCiAi29iTdjBVt692jErDyWbcl_VYjW_g==[Validation Process,width=600,height=650]

//[Edit this diagram](https://niolesk.top/#https://kroki.io/pikchr/svg/eNq9mE1zqkgUhvf8ii4nCxmVggY03qpZ2KCrVN2MqZmaxd0gktg1BryA0fvvp7tpPrtJAmbIIqWc9pz3PP0elL6LwR9A1yAOld_AKUpwiqMQRM_Ai-PoAnAIdvgF7KJrkCh33oksNrQFVFbG7hu9CmJvD-zTFYzWT48u2AY_z0GSjtiH_OgYxUC_OraNDAM84-ORvFu7C9ek71Jwwfv0AAz797sYHAL8ckgBJK-VNLimsoReCkhdnvdywGmgKKhNSHKKwiTopIQk17JXXA29wF_-UC6YBLQLV6EFYALGumbZU12tK65WJotRU_IK-t-Aj2P_GID0gP1_a_85FMqkITuXEOYSEiZhOtM1U1X20SUESrZr9NPKymyS-efJBX97R7z36CaPwGj8F3qY_Xkml56xzy6uTqcjf8nRz6Bmaddkr46IADnIDVrb7oKBpBrrKGfEXVa5q7dqoK2buwKNsYSO5RAbfAVT9CFTdDPTzBw9oZocak-WQm3aswymdW506UT7ADzgJE3IfpKSZFPA9nwk_8e6AajvZz5ZciQrZm8srPlvnprNQGuHmw103FqH4z3JMGZ9TokyLVBVEsun0WyZRrq82DY7n8abNFMy1lkkY79DZpWmMd6dU1IBnRMcBkmzIHCi11dye3UeKou1xD90J0XU8QHrxMfQdAmf25VTXrbIazVvzovjxXscEoemv4oSEOT3elANoy0v0IbFXa9Xm7l8RLpiKW3TQyDNNpfMUbfuk9OQ7aMe7bcppOlk_S_EaWEuKm9adDadmHwtxvRnh2A-s26-cuH2E1OzhhvdXX7F1MDq1PwPHVB-C8n03Av--bAQ86hYpQOjniMEKx7qq5KmvJf4qBcHatahQKD-IOQyaU4ZieWnJup7eghisaZV8yJf9JlJcm3XWc-_YpLMDyapr3LKaymZIENvWuf9CtSYjfQdoPQcHbN0TGd17FFA30k6NzoMjV3mf4wj_xwPC8CquKKnSMbBkHGATQ5Pp8CnP5DfrVAuGhJD4YOeGhkFKLlvdJ8Dcl8aZBBQv0EQ5bEHOF3Wu3hE8P0driQzjQ_XdcX9XYSxfg1Zv30cT5IPZXnU2_JSkYyD1PPCw_pjHMx-Vh-PpSVqD9BDwrBLI9yklBGRPdcbVqszttExkNZggUEhiI74pDjWtyX5DoB6eTokOQsqDgJZK42ToSS_qRZHQ4Y2VxV0c04qtXLcRHIqCL-g6GqUe2TQTfqhAPrXPFibsHo8yKlm5yf0HCucUoVaopIfVeTxjixVy0TsxIuR1zWWxdtFbwFYQT8TRB8Ip7pm2sVndsEBh3t2_MqvsM7YiSbv-SX2fuUtwEYLXB7vr_RApbE8llumIjXzCI_zc1c41buLy07ynuPolVkxAWnEfsiGBNL4zjvRo9zKGhpKyhBbbbevtoXVqznZiFrVeV510Z5nIea5b-a5z_Ms2_MsxTzk-7GRiF5JspghxIwiBoUYzGPUZrUYqqOdtKOdiGgn7Wjrq5toUR3tpB1tPU8TLaqjnbSjrecR0KICLRLQogItEtCiAi29iTdjBVt692jErDyWbcl_VYjW_g==)

_Figure 1. ESPD Validation Process_

=== ESPD Request Validation

[arabic]
. *XSD Validation* against QualificationApplicationRequest-2.4.xsd
. *Code list validations* (common for both Request and Response):
[loweralpha]
.. Validation of the code list values: `01-ESPD-codelist-values.cva`
.. Validation of the identification of the code list: `01-ESPD-common-cl-attributes.sch`
.. Restrictions on code list attribute values: `01-ESPD-common-cl-values-restrictions.sch`
. Business rules related to the *cardinality* of the schema: `02-ESPD-req-cardinality-br.sch`
. Business rules used to validate the *criteria data structure*:
[loweralpha]
.. Validations common for Request and Response: `03-ESPD-common-criterion-br.sch`
.. Validations specific for Request: `03-ESPD-req-criterion-br.sch`
. *Other* business rules:
[loweralpha]
.. Common validations (schemeAgencyID for identifiers): `04-ESPD-common-other-br.sch`
.. Specific business rules for Request: `04-ESPD-req-other-br.sch`
.. Business rules related to the procurer: `05-ESPD-req-procurer-br.sch`
.. Specific business rules: `05-ESPD-req-specific-br.sch`

=== ESPD Response Validation

[arabic]
. *XSD Validation* against QualificationApplicationResponse-2.4.xsd
. *Code list validations* (common for both Request and Response):
[loweralpha]
.. Validation of the code list values: `01-ESPD-codelist-values.cva`
.. Validation of the identification of the code list: `01-ESPD-common-cl-attributes.sch`
.. Restrictions on code list attribute values: `01-ESPD-common-cl-values-restrictions.sch`
. Business rules related to the *cardinality* of the schema: `02-ESPD-resp-cardinality-br.sch`
. Business rules used to validate the *criteria data structure*:
[loweralpha]
.. Validations common for Request and Response: `03-ESPD-common-criterion-br.sch`
.. Validations specific for Response: `03-ESPD-resp-criterion-br.sch`
. *Other* business rules:
[loweralpha]
.. Common validations: `04-ESPD-common-other-br.sch`
.. Specific business rules for Response: `04-ESPD-resp-other-br.sch`
.. Business rules related to the economic operator: `05-ESPD-resp-eo-br.sch`
.. Response-specific business rules: `05-ESPD-resp-specific-br.sch`
.. Pre-qualification system rules: `05-ESPD-resp-qualification-br.sch`
.. Role-dependent business rules: `05-ESPD-resp-role-br.sch`

== Criterion Identifier Validation

Each top-level criterion is defined in eCertis and has a *Universally Unique Identifier (UUID)* supplied by eCertis:

[arabic]
. The criterion UUID is mandatory and is maintained by the Publications Office.
. The criterion UUIDs can be found in the link:{url-tree}/criterion/espd-edm.json[espd-edm.json] file.

The `cbc:ID` of each of the following elements is validated against the eCertis reference data (matched by identifier, and checked for the expected structure):

[cols="1,3",options="header"]
|===
|Element |Path |Identifier form

|Criterion
|`cac:TenderingCriterion/cbc:ID`
|eCertis *UUID*

|Property Group
|`cac:TenderingCriterionPropertyGroup/cbc:ID`
|XML Path Like ID

|Property
|`cac:TenderingCriterionProperty/cbc:ID`
|XML Path Like ID
|===

NOTE: Only the top-level criterion `cbc:ID` is a UUID. The property groups and properties nested below it carry *XML Path Like IDs* (see <<_xml_path_like_id,XML Path Like ID>> below), not UUIDs — although their `cbc:ID` values are still validated against the eCertis reference structure.

=== Tendering Criterion Validation

The validation of each criterion (`cac:TenderingCriterion` element) checks:

[arabic]
. `cbc:ID`, `cbc:CriterionTypeCode`, `cbc:Name` and `cbc:Description` are mandatory;
. `cbc:ID` values match with the ones supplied by eCertis;
. `cac:TenderingCriterionPropertyGroup` structure matches the expected QUESTION_GROUP or REQUIREMENT_GROUP.

=== Tendering Criterion Property Group and Subgroup

The same validations are executed for the first level group of properties and sub-groups of properties:

[arabic]
. The `cbc:ID` and `cbc:PropertyGroupTypeCode` are mandatory;
. `cac:SubsidiaryTenderingCriterionPropertyGroup` matches with QUESTION_SUBGROUP or REQUIREMENT_SUBGROUP;
. `cac:TenderingCriterionProperty` structure matches with QUESTION or REQUIREMENT or CAPTION.

=== Tendering Criterion Property

The validation of `cac:TenderingCriterionProperty` checks:

[arabic]
. `cbc:TypeCode` and `cbc:ValueDataTypeCode` are mandatory elements;
. `cbc:ID` and `cbc:Description` elements are mandatory (values not validated);
. If `cbc:TypeCode` value is "CAPTION", `cbc:ValueDataTypeCode` value must be "NONE".

=== XML Path Like ID

Starting with ESPD v4.0.0, UUIDs for all sub-elements are replaced by XML Path Like IDs in the data structure, except for the top-level Exclusion Grounds and Selection Criteria elements. For further details, see xref:how-criteria-work.adoc[How Criteria Work]. The XML Path Like ID is built programmatically.

== Code List Validation (CVA)

Business rules related to code lists validate values and their mandatory attributes. This uses an extra step before the Schematron process: link:https://www.oasis-open.org/committees/tc_home.php?wg_abbrev=codelist[Genericode] (GC) files as input.

The process:

[arabic]
. *Generation of Genericode (GC) files* — found in the link:{url-tree}/codelists/[codelists folder].
. *Design and implementation of the CVA file* (Context and Value Association) — specifies the association between XML elements and code list files.
. *Execution*:
[loweralpha]
.. Transformation of CVA files into SCH files.
.. Transformation of SCH files into XSLT.
.. Execution of the validations and generation of the final report.

image::https://kroki.io/pikchr/svg/eNqVls9zmzoQx-_8FTtMD03TUATGxOmPGbDdTi6vM22mp14wyLZSDB6BYzun_gE9vuPrpX_a-0u6AglsNS4mM4mJ0fezu9rVrp5xeAu25bDMSPJtZhgBuYFZvgMeJeCtd2CO84RCyooSwk3BMloUwDcpLUyYsQUuTROI8zTnsF2yksKcpSnYO_u9Nxh5sGVJuQTivXjGEe3cQEl3JZifaBqVLM9gRsstpRkQZCgzUZYAeXUJNKUrmpXFjQnp_QZffDVqQ_aOjJzxYIxfRCU67yEmzbcQELiE51fE8l7aF0bgKmv_f_8Fd0uqgGgqKyOWFZBnFPI5lPjuIUo3tFD_ceEfTVqnXnf5cK374FQ-DA59CMqSs9mmbO2oECHitPoCPSqgWNOYzRlNrL9bJRZ50qoR-JGy-8YEJXVCJxz6KN0yzIm1BUQEBD-v4Ln9EnftwuBssSxRPlPycb7JSr5vIcOJY5OpBvEji1YUiwyqsP1YAcTmBQuaxfvbSUsJbdd1bZ0yayh1Av1EUd5-NTvi8GNdTJX49vPHVuyP3IlDdHHSiOu0-XMl7jZMG61daxeHsX-hvMBC7w5-rruw7BH8ohH7tZgpsWPZrbgpniPxshETIVY1cH_-FrBjQuB_O9yCf6IV7Yr-XhHsUU1Ie0T_TU_96iD14JLh8Ip0bUKqM7Lzw1_p2lxp33VJM33n1o3rd11Fm-vaXXPoX3XZXevafc8Tv9PL9fHsmPfHto1QThwTTvxIl8Qgutuv6allJhSrCIdPNZLk4HFw8MCSipIGIp5rT7KmbxWy_dnW8AI7MI7B0JHuyLaVYIMW3ZjrfDF5XoTYQPER8fiEfw_5-A3i5UCckGkwndYmKnzVlmpigSfECF1pV7aM_uYcYY5lD6xgs1QAI0kkogkcmhrIF5-XOZfns68x92-xHWTsz_2rXMCsq7Rr6X0ijd7TWZRJfMR6uhT1hKcPh5jMImnSOFFEEQyabYN6ImOnUhYSlZ5g2oen54SorQ_e98G4J93yFO9DH95Ad2uoMLd9MN5Jt3zJsyzrj9rqog51564lTPTE853zTzo3UsF-7MO7PnbLGGMBx4zHKcXWY6qOYzltgcZqPMbG2Dlz8Vosds9ajAdcLB6ctxj9jw0j4hzvi3Oer2CMtQ5lDmPXotXO4C315w8Toln-gFfg6uJZXfHVb3vV5zQ5ImGV0wo1ELslWf_9q1gnKAuOV3_D-A0izaAt[Code list business rules,width=650,height=350]

_Figure 2. Code list validation architecture_

== Testing with the Interoperability Testbed

The https://www.itb.ec.europa.eu/espd/upload[Interoperability Testbed] allows developers and integrators to test the validity of their ESPD XML instances by uploading them and launching the validation online.

All the ESPD-EDM artefacts necessary to perform the validation are set up in the testbed — no local installation is required.

== Further information

* For the general Schematron architecture, see xref:common-concepts.adoc[Common Concepts].
* For the complete list of business rules, see xref:business-rules.adoc[Business Rules].
* For code list details, see xref:code-lists.adoc[Code Lists].

include::partial$feedback.adoc[]
