site:
  title: ESPD Documentation
  start_page: home::index.adoc

content:
  edit_url: false
  sources:

  ### Local content
  - url: ..
    start_path: .
    branches: HEAD

urls:
  redirect_facility: static
  # html_extension_style: indexify
  latest_version_segment: latest

ui:
  bundle:
    url: https://github.com/OP-TED/antora-eui/releases/download/ui-bundle/eForms-SDK-customisations/ui-bundle.zip
    snapshot: true
