name: Word to ASCIIDoc converter

on: workflow_dispatch
# manual triggering only

jobs:
  convert_via_pandoc:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4.1.7
        with:
          ref: pandoc
          # use pandoc branch for storing the input Word file and to collect all output files
      - name: list files to conver
        id: files_list
        run: |
          mkdir output  # create output dir
          # list all ESPD*.docx files as input argumets for conversion
          # echo "files=$(printf '"%s" ' ESPD*.docx)" > $GITHUB_OUTPUT
          echo "files=$(ls -t ESPD*.docx | grep -v "TEMPLATE" | head -n 1)" > $GITHUB_OUTPUT
      - uses: docker://pandoc/latex:latest
        with:
          args: --standalone --wrap=none --markdown-headings=atx --extract-media=output/extracted-media --from=docx --to=asciidoc --output=output/${{steps.files_list.outputs.files}}.adoc ${{ steps.files_list.outputs.files }}         
      - name: fix format
        id: sed_script
        run: |
           sed -i '0,/\[width/s/^\[width.*\]$/[cols=","]/' output/meeting_minutes.adoc
           # fix first table
           sed -i '0,/\[width/s/^\[width.*\]$/[cols=",",options="header"]/' output/meeting_minutes.adoc
           # fix second table
           sed -i 's/== Summary/:sectnums:\n:sectnumlevels: 4\n\n== Summary/' output/meeting_minutes.adoc
           # add numbering before == Summary ... section
      - uses: docker://pandoc/latex:latest
        with:
          args: --standalone --from=docx --to=pdf --output=output/${{steps.files_list.outputs.files}}.pdf ${{ steps.files_list.outputs.files }}
      - uses: actions/upload-artifact@v4.3.4
        with:
          name: asciidoc
          path: output
