name: Word default template

on: 
  workflow_dispatch

jobs:
  convert_via_pandoc:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4.1.7
        with:
          ref: pandoc
          # use pandoc branch for storing the input Word file and to collect all output files
      - name: export default Word template
      - uses: docker://pandoc/latex:latest
        with:
          args: --output=custom-reference.docx --print-default-data-file reference.docx          
      - uses: actions/upload-artifact@v4.3.4
        with:
          name: docx_template
          path: output
