name: Word to ASCIIDoc converter

on: workflow_dispatch
# manual triggering only

jobs:
  convert_via_pandoc:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4.1.7
        with:
          ref: pandoc
          # use pandoc branch for storing the input Word file and to collect all output files
      - name: list files to conver
        id: files_list
        run: |
          mkdir output  # create output dir
          # list all ESPD*.docx files as input argumets for conversion
          echo "files=$(printf '"%s" ' ESPD*.docx)" > $GITHUB_OUTPUT
      - uses: docker://pandoc/latex:latest
        with:
          args: --reference-doc=pandoc-reference.docx --from=docx --to=asciidoc --output=output/meeting_minutes.adoc ${{ steps.files_list.outputs.files }}         
      - uses: actions/upload-artifact@v4.3.4
        with:
          name: asciidoc
          path: output
