name: Word to ASCIIDoc converter

on: 
  workflow_dispatch:
  push:
    branches:
      - pandoc

jobs:
  convert_via_pandoc:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4.1.7
        with:
          ref: pandoc
          # use pandoc branch for storing the input Word file and to collect all output files
      - uses: docker://pandoc/latex:latest
        with:
          args: --reference-doc=pandoc-reference.docx --from=docx --to=asciidoc --output=meeting_minutes.adoc ESPD_test.docx          
      - uses: actions/upload-artifact@v4.3.4
        with:
          name: asciidoc
          path: output
